#!/usr/bin/env python3
"""
Étend la base de données de vocabulaire de +50%.
Génère data.js (vocabulaire) et verbs-data.js (verbes conjugués).
"""
import json

# ============================================================
# NOMS — Ajout de 170 nouveaux noms (340 → 510)
# Focus : A2-B2, vocabulaire moins basique, plus de profondeur
# ============================================================
NOMS_EXISTANTS = [
    # === FAMILLE & PERSONNES (A1-A2) ===
    ("le père", "der Vater", "der", "A1", "👨", None),
    ("la mère", "die Mutter", "die", "A1", "👩", None),
    ("le frère", "der Bruder", "der", "A1", "👦", None),
    ("la sœur", "die Schwester", "die", "A1", "👧", None),
    ("l'enfant", "das Kind", "das", "A1", "🧒", None),
    ("le fils", "der Sohn", "der", "A1", "👶", None),
    ("la fille", "die Tochter", "die", "A1", "👧", None),
    ("le grand-père", "der Großvater", "der", "A1", "👴", None),
    ("la grand-mère", "die Großmutter", "die", "A1", "👵", None),
    ("l'oncle", "der Onkel", "der", "A1", "🧔", None),
    ("la tante", "die Tante", "die", "A1", "👩‍🦰", None),
    ("le cousin", "der Cousin", "der", "A1", "👨", None),
    ("la cousine", "die Cousine", "die", "A1", "👩", None),
    ("le mari", "der Mann", "der", "A1", "🤵", None),
    ("la femme", "die Frau", "die", "A1", "👰", None),
    ("les parents", "die Eltern", "die", "A1", "👨‍👩‍👧", None),
    ("l'ami", "der Freund", "der", "A1", "🧑‍🤝‍🧑", None),
    ("l'amie", "die Freundin", "die", "A1", "🧑‍🤝‍🧑", None),
    ("le bébé", "das Baby", "das", "A1", "👶", None),
    ("le voisin", "der Nachbar", "der", "A2", "🏘️", None),
    ("la personne", "die Person", "die", "A1", "🧑", None),
    ("le garçon", "der Junge", "der", "A1", "👦", None),
    ("le monsieur", "der Herr", "der", "A1", "🤵", None),
    ("la dame", "die Dame", "die", "A1", "👩", None),
    ("le neveu", "der Neffe", "der", "A2", "👦", None),
    ("la nièce", "die Nichte", "die", "A2", "👧", None),
    ("la famille", "die Familie", "die", "A1", "👨‍👩‍👧‍👦", None),
    ("le couple", "das Paar", "das", "A2", "💑", None),
    ("l'adulte", "der Erwachsene", "der", "A2", "🧑", None),
    ("le jumeau", "der Zwilling", "der", "B1", "👯", None),

    # === CORPS HUMAIN (A1-B2) ===
    ("la tête", "der Kopf", "der", "A1", "🗣️", None),
    ("les cheveux", "die Haare", "die", "A1", "💇", None),
    ("l'œil", "das Auge", "das", "A1", "👁️", None),
    ("l'oreille", "das Ohr", "das", "A1", "👂", None),
    ("le nez", "die Nase", "die", "A1", "👃", None),
    ("la bouche", "der Mund", "der", "A1", "👄", None),
    ("la dent", "der Zahn", "der", "A1", "🦷", None),
    ("la langue", "die Zunge", "die", "A2", "👅", None),
    ("le visage", "das Gesicht", "das", "A1", "😀", None),
    ("le cou", "der Hals", "der", "A2", "🧣", None),
    ("l'épaule", "die Schulter", "die", "A2", "💪", None),
    ("le bras", "der Arm", "der", "A1", "💪", None),
    ("la main", "die Hand", "die", "A1", "✋", None),
    ("le doigt", "der Finger", "der", "A1", "👆", None),
    ("la jambe", "das Bein", "das", "A1", "🦵", None),
    ("le pied", "der Fuß", "der", "A1", "🦶", None),
    ("le dos", "der Rücken", "der", "A2", "🤸", None),
    ("le ventre", "der Bauch", "der", "A2", "🤰", None),
    ("le cœur", "das Herz", "das", "A1", "❤️", None),
    ("la peau", "die Haut", "die", "A2", "🧴", None),
    ("le corps", "der Körper", "der", "A1", "🧍", None),
    ("le sang", "das Blut", "das", "A2", "🩸", None),
    ("le squelette", "das Skelett", "das", "B1", "💀", None),
    ("le muscle", "der Muskel", "der", "B1", "💪", None),
    ("le cerveau", "das Gehirn", "das", "B1", "🧠", None),
    ("le poumon", "die Lunge", "die", "B1", "🫁", None),
    ("le foie", "die Leber", "die", "B1", "🍷", None),
    ("le rein", "die Niere", "die", "B2", "🫘", None),
    ("le squelette", "das Skelett", "das", "B2", "💀", None),
    ("la cheville", "der Knöchel", "der", "B1", "🦶", None),

    # === MAISON & MEUBLES ===
    ("la maison", "das Haus", "das", "A1", "🏠", "1568605114967-8130f3a36994"),
    ("l'appartement", "die Wohnung", "die", "A1", "🏢", None),
    ("la chambre", "das Zimmer", "das", "A1", "🛏️", None),
    ("la cuisine", "die Küche", "die", "A1", "🍳", None),
    ("la salle de bain", "das Badezimmer", "das", "A1", "🛁", None),
    ("le salon", "das Wohnzimmer", "das", "A1", "🛋️", None),
    ("les toilettes", "die Toilette", "die", "A1", "🚽", None),
    ("le lit", "das Bett", "das", "A1", "🛏️", None),
    ("la table", "der Tisch", "der", "A1", "🪑", "1577140917170-285929fb55b7"),
    ("la chaise", "der Stuhl", "der", "A1", "💺", "1503602642458-232111445657"),
    ("le canapé", "das Sofa", "das", "A1", "🛋️", None),
    ("l'armoire", "der Schrank", "der", "A1", "🚪", None),
    ("la lampe", "die Lampe", "die", "A1", "💡", None),
    ("le miroir", "der Spiegel", "der", "A2", "🪞", None),
    ("la télévision", "der Fernseher", "der", "A1", "📺", None),
    ("le réfrigérateur", "der Kühlschrank", "der", "A1", "🧊", None),
    ("le four", "der Ofen", "der", "A2", "🔥", None),
    ("la porte", "die Tür", "die", "A1", "🚪", "1558618666-fcd25c85cd64"),
    ("la fenêtre", "das Fenster", "das", "A1", "🪟", "1502005229762-cf1b2da7c5d6"),
    ("le mur", "die Wand", "die", "A2", "🧱", None),
    ("le plafond", "die Decke", "die", "B1", "⬜", None),
    ("le sol", "der Boden", "der", "A2", "⬛", None),
    ("l'escalier", "die Treppe", "die", "A2", "🪜", None),
    ("le jardin", "der Garten", "der", "A1", "🌳", None),
    ("le balcon", "der Balkon", "der", "A2", "🏠", None),
    ("la cave", "der Keller", "der", "A2", "🏚️", None),
    ("le grenier", "der Dachboden", "der", "B1", "🏠", None),
    ("le couloir", "der Flur", "der", "A2", "🚪", None),
    ("le toit", "das Dach", "das", "A2", "🏠", None),
    ("la clé", "der Schlüssel", "der", "A1", "🔑", None),
    ("le tapis", "der Teppich", "der", "A2", "🟫", None),
    ("le rideau", "der Vorhang", "der", "B1", "🪟", None),
    ("l'oreiller", "das Kissen", "das", "A2", "🛏️", None),
    ("la couverture", "die Decke", "die", "A2", "🛏️", None),
    ("la serviette", "das Handtuch", "das", "A2", "🧻", None),
    ("le savon", "die Seife", "die", "A2", "🧼", None),

    # === NOURRITURE ===
    ("le pain", "das Brot", "das", "A1", "🍞", "1509440159596-0249088772ff"),
    ("le beurre", "die Butter", "die", "A1", "🧈", None),
    ("le fromage", "der Käse", "der", "A1", "🧀", "1486297678162-eb2a19b0a32d"),
    ("le lait", "die Milch", "die", "A1", "🥛", None),
    ("l'œuf", "das Ei", "das", "A1", "🥚", None),
    ("la viande", "das Fleisch", "das", "A1", "🥩", None),
    ("le poulet", "das Hähnchen", "das", "A1", "🍗", None),
    ("le poisson", "der Fisch", "der", "A1", "🐟", "1535591273668-578e31182c4f"),
    ("le légume", "das Gemüse", "das", "A1", "🥬", None),
    ("le fruit", "das Obst", "das", "A1", "🍎", None),
    ("la pomme", "der Apfel", "der", "A1", "🍎", "1568702846914-96b305d2aaeb"),
    ("la banane", "die Banane", "die", "A1", "🍌", None),
    ("l'orange", "die Orange", "die", "A1", "🍊", None),
    ("la tomate", "die Tomate", "die", "A1", "🍅", None),
    ("la pomme de terre", "die Kartoffel", "die", "A1", "🥔", None),
    ("la carotte", "die Karotte", "die", "A1", "🥕", None),
    ("la salade", "der Salat", "der", "A1", "🥗", None),
    ("le riz", "der Reis", "der", "A1", "🍚", None),
    ("les pâtes", "die Nudeln", "die", "A1", "🍝", None),
    ("la soupe", "die Suppe", "die", "A1", "🍲", None),
    ("le gâteau", "der Kuchen", "der", "A1", "🍰", None),
    ("le chocolat", "die Schokolade", "die", "A1", "🍫", None),
    ("le sucre", "der Zucker", "der", "A1", "🍬", None),
    ("le sel", "das Salz", "das", "A1", "🧂", None),
    ("le poivre", "der Pfeffer", "der", "A2", "🧂", None),
    ("l'eau", "das Wasser", "das", "A1", "💧", "1548839140-29a749e1cf4d"),
    ("le café", "der Kaffee", "der", "A1", "☕", "1509042239860-f550ce710b93"),
    ("le thé", "der Tee", "der", "A1", "🍵", "1576092768241-dec231879fc3"),
    ("le jus", "der Saft", "der", "A1", "🧃", None),
    ("la bière", "das Bier", "das", "A1", "🍺", "1535958636474-b021ee887b13"),
    ("le vin", "der Wein", "der", "A1", "🍷", "1510812431401-41d2bd2722f3"),
    ("le yaourt", "der Joghurt", "der", "A2", "🥛", None),
    ("la confiture", "die Marmelade", "die", "A2", "🍓", None),
    ("le miel", "der Honig", "der", "A2", "🍯", None),
    ("la glace", "das Eis", "das", "A1", "🍦", None),
    ("le citron", "die Zitrone", "die", "A1", "🍋", None),
    ("la fraise", "die Erdbeere", "die", "A1", "🍓", None),
    ("la cerise", "die Kirsche", "die", "A2", "🍒", None),
    ("le raisin", "die Traube", "die", "A2", "🍇", None),
    ("le concombre", "die Gurke", "die", "A2", "🥒", None),
    ("l'oignon", "die Zwiebel", "die", "A2", "🧅", None),
    ("l'ail", "der Knoblauch", "der", "B1", "🧄", None),
    ("le champignon", "der Pilz", "der", "A2", "🍄", None),
    ("la saucisse", "die Wurst", "die", "A1", "🌭", None),
    ("le jambon", "der Schinken", "der", "A2", "🍖", None),
    ("le restaurant", "das Restaurant", "das", "A1", "🍴", None),
    ("le menu", "die Speisekarte", "die", "A2", "📋", None),
    ("l'addition", "die Rechnung", "die", "A2", "🧾", None),
    ("le petit-déjeuner", "das Frühstück", "das", "A1", "🥐", None),
    ("le déjeuner", "das Mittagessen", "das", "A1", "🍽️", None),
    ("le dîner", "das Abendessen", "das", "A1", "🍽️", None),
    ("le repas", "die Mahlzeit", "die", "A2", "🍽️", None),
    ("le snack", "der Snack", "der", "A2", "🍿", None),

    # === VÊTEMENTS ===
    ("la chemise", "das Hemd", "das", "A1", "👔", None),
    ("le pantalon", "die Hose", "die", "A1", "👖", None),
    ("la robe", "das Kleid", "das", "A1", "👗", None),
    ("la jupe", "der Rock", "der", "A1", "👗", None),
    ("le manteau", "der Mantel", "der", "A1", "🧥", None),
    ("la veste", "die Jacke", "die", "A1", "🧥", None),
    ("la chaussure", "der Schuh", "der", "A1", "👟", None),
    ("la chaussette", "die Socke", "die", "A1", "🧦", None),
    ("le chapeau", "der Hut", "der", "A2", "🎩", None),
    ("l'écharpe", "der Schal", "der", "A2", "🧣", None),
    ("le gant", "der Handschuh", "der", "A2", "🧤", None),
    ("la ceinture", "der Gürtel", "der", "A2", "👔", None),
    ("la cravate", "die Krawatte", "die", "A2", "👔", None),
    ("le t-shirt", "das T-Shirt", "das", "A1", "👕", None),
    ("le pull", "der Pullover", "der", "A1", "🧶", None),
    ("la veste", "die Jacke", "die", "A1", "🧥", None),
    ("le pyjama", "der Schlafanzug", "der", "A2", "🩱", None),
    ("le maillot", "der Badeanzug", "der", "A2", "🩱", None),
    ("la casquette", "die Mütze", "die", "A2", "🧢", None),
    ("les lunettes", "die Brille", "die", "A1", "👓", None),

    # === ANIMAUX ===
    ("le chien", "der Hund", "der", "A1", "🐕", "1543466835-00a7907e9de1"),
    ("le chat", "die Katze", "die", "A1", "🐱", "1514888286974-6c03e2ca1dba"),
    ("l'oiseau", "der Vogel", "der", "A1", "🐦", "1452570053594-1b985d6ea890"),
    ("le cheval", "das Pferd", "das", "A1", "🐴", None),
    ("la vache", "die Kuh", "die", "A1", "🐄", None),
    ("le cochon", "das Schwein", "das", "A1", "🐖", None),
    ("le mouton", "das Schaf", "das", "A1", "🐑", None),
    ("la poule", "das Huhn", "das", "A1", "🐔", None),
    ("le lapin", "das Kaninchen", "das", "A2", "🐰", None),
    ("la souris", "die Maus", "die", "A2", "🐭", None),
    ("l'éléphant", "der Elefant", "der", "A1", "🐘", None),
    ("le lion", "der Löwe", "der", "A1", "🦁", None),
    ("le tigre", "der Tiger", "der", "A1", "🐯", None),
    ("l'ours", "der Bär", "der", "A2", "🐻", None),
    ("le singe", "der Affe", "der", "A2", "🐵", None),
    ("le loup", "der Wolf", "der", "B1", "🐺", None),
    ("le renard", "der Fuchs", "der", "B1", "🦊", None),
    ("la girafe", "die Giraffe", "die", "A2", "🦒", None),
    ("le serpent", "die Schlange", "die", "A2", "🐍", None),
    ("l'abeille", "die Biene", "die", "A2", "🐝", None),
    ("le papillon", "der Schmetterling", "der", "A2", "🦋", None),
    ("l'araignée", "die Spinne", "die", "B1", "🕷️", None),
    ("la grenouille", "der Frosch", "der", "A2", "🐸", None),
    ("le canard", "die Ente", "die", "A2", "🦆", None),
    ("le poussin", "das Küken", "das", "B1", "🐥", None),

    # === TRANSPORTS ===
    ("la voiture", "das Auto", "das", "A1", "🚗", "1494976388531-d1058494cdd8"),
    ("le train", "der Zug", "der", "A1", "🚂", "1474487548417-781cb71495f3"),
    ("l'avion", "das Flugzeug", "das", "A1", "✈️", "1436491865332-7a61a109cc05"),
    ("le bus", "der Bus", "der", "A1", "🚌", None),
    ("le vélo", "das Fahrrad", "das", "A1", "🚲", "1485965120184-e220f721d03e"),
    ("le bateau", "das Boot", "das", "A1", "⛵", None),
    ("le taxi", "das Taxi", "das", "A1", "🚕", None),
    ("le métro", "die U-Bahn", "die", "A1", "🚇", None),
    ("le tram", "die Straßenbahn", "die", "A2", "🚊", None),
    ("la moto", "das Motorrad", "das", "A1", "🏍️", None),
    ("le camion", "der Lastwagen", "der", "A2", "🚚", None),
    ("la rue", "die Straße", "die", "A1", "🛣️", None),
    ("la route", "die Straße", "die", "A1", "🛣️", None),
    ("la gare", "der Bahnhof", "der", "A1", "🚉", None),
    ("l'aéroport", "der Flughafen", "der", "A1", "🛫", None),
    ("le port", "der Hafen", "der", "B1", "⚓", None),
    ("l'arrêt", "die Haltestelle", "die", "A2", "🚏", None),
    ("le billet", "die Fahrkarte", "die", "A1", "🎫", None),
    ("le voyage", "die Reise", "die", "A1", "🧳", None),
    ("la valise", "der Koffer", "der", "A1", "🧳", None),
    ("le sac", "die Tasche", "die", "A1", "👜", None),
    ("le passeport", "der Reisepass", "der", "A2", "📔", None),
    ("le siège", "der Sitz", "der", "A2", "💺", None),
    ("le pneu", "der Reifen", "der", "B1", "🛞", None),
    ("le moteur", "der Motor", "der", "B1", "🔧", None),

    # === TRAVAIL & ÉCOLE ===
    ("l'école", "die Schule", "die", "A1", "🏫", None),
    ("l'université", "die Universität", "die", "A1", "🎓", None),
    ("la classe", "die Klasse", "die", "A1", "👨‍🏫", None),
    ("le professeur", "der Lehrer", "der", "A1", "👨‍🏫", None),
    ("l'étudiant", "der Student", "der", "A1", "👨‍🎓", None),
    ("l'élève", "der Schüler", "der", "A1", "🧑‍🎓", None),
    ("le livre", "das Buch", "das", "A1", "📚", "1544947950-fa07a98d237f"),
    ("le cahier", "das Heft", "das", "A1", "📓", None),
    ("le stylo", "der Kugelschreiber", "der", "A1", "🖊️", None),
    ("le crayon", "der Bleistift", "der", "A1", "✏️", None),
    ("le papier", "das Papier", "das", "A1", "📄", None),
    ("le bureau", "der Schreibtisch", "der", "A1", "🪑", None),
    ("l'ordinateur", "der Computer", "der", "A1", "💻", "1496181133206-80ce9b88a853"),
    ("le travail", "die Arbeit", "die", "A1", "💼", None),
    ("l'entreprise", "die Firma", "die", "A2", "🏢", None),
    ("le bureau", "das Büro", "das", "A1", "🏢", None),
    ("le patron", "der Chef", "der", "A2", "👔", None),
    ("le collègue", "der Kollege", "der", "A2", "🤝", None),
    ("le métier", "der Beruf", "der", "A1", "💼", None),
    ("le médecin", "der Arzt", "der", "A1", "👨‍⚕️", None),
    ("l'infirmier", "der Krankenpfleger", "der", "A2", "👨‍⚕️", None),
    ("le policier", "der Polizist", "der", "A1", "👮", None),
    ("le pompier", "der Feuerwehrmann", "der", "A2", "👨‍🚒", None),
    ("le cuisinier", "der Koch", "der", "A2", "👨‍🍳", None),
    ("le boulanger", "der Bäcker", "der", "A2", "🥖", None),
    ("le serveur", "der Kellner", "der", "A2", "🍽️", None),
    ("le vendeur", "der Verkäufer", "der", "A2", "🛒", None),
    ("le chauffeur", "der Fahrer", "der", "A2", "🚗", None),
    ("l'ingénieur", "der Ingenieur", "der", "A2", "🔧", None),
    ("l'artiste", "der Künstler", "der", "A2", "🎨", None),
    ("le journaliste", "der Journalist", "der", "B1", "📰", None),
    ("l'avocat", "der Anwalt", "der", "B1", "⚖️", None),
    ("la leçon", "die Lektion", "die", "A1", "📖", None),
    ("le devoir", "die Hausaufgabe", "die", "A1", "📝", None),
    ("l'examen", "die Prüfung", "die", "A1", "📋", None),
    ("la note", "die Note", "die", "A2", "💯", None),
    ("la matière", "das Fach", "das", "A2", "📚", None),
    ("la réunion", "die Besprechung", "die", "B1", "💼", None),
    ("le projet", "das Projekt", "das", "A2", "📊", None),
    ("le rapport", "der Bericht", "der", "B1", "📄", None),
    ("la pause", "die Pause", "die", "A1", "☕", None),

    # === TEMPS & NATURE ===
    ("le jour", "der Tag", "der", "A1", "🌞", None),
    ("la nuit", "die Nacht", "die", "A1", "🌃", None),
    ("le matin", "der Morgen", "der", "A1", "🌅", None),
    ("le soir", "der Abend", "der", "A1", "🌆", None),
    ("la semaine", "die Woche", "die", "A1", "📅", None),
    ("le mois", "der Monat", "der", "A1", "📅", None),
    ("l'année", "das Jahr", "das", "A1", "📅", None),
    ("l'heure", "die Stunde", "die", "A1", "🕐", None),
    ("la minute", "die Minute", "die", "A1", "⏱️", None),
    ("la seconde", "die Sekunde", "die", "A1", "⏱️", None),
    ("le moment", "der Moment", "der", "A2", "⌛", None),
    ("le temps", "die Zeit", "die", "A1", "⏰", None),
    ("le soleil", "die Sonne", "die", "A1", "☀️", "1532978879514-6cb1f6b3320b"),
    ("la lune", "der Mond", "der", "A1", "🌙", "1532693322450-2cb5c511067d"),
    ("l'étoile", "der Stern", "der", "A2", "⭐", None),
    ("le ciel", "der Himmel", "der", "A1", "🌌", None),
    ("le nuage", "die Wolke", "die", "A1", "☁️", None),
    ("la pluie", "der Regen", "der", "A1", "🌧️", None),
    ("la neige", "der Schnee", "der", "A1", "❄️", None),
    ("le vent", "der Wind", "der", "A1", "💨", None),
    ("le feu", "das Feuer", "das", "A2", "🔥", None),
    ("la terre", "die Erde", "die", "A1", "🌍", None),
    ("la mer", "das Meer", "das", "A1", "🌊", "1505142468610-359e7d316be0"),
    ("le lac", "der See", "der", "A1", "🏞️", None),
    ("la rivière", "der Fluss", "der", "A1", "🏞️", None),
    ("la forêt", "der Wald", "der", "A1", "🌲", None),
    ("la montagne", "der Berg", "der", "A1", "⛰️", "1464822759023-fed622ff2c3b"),
    ("la plage", "der Strand", "der", "A1", "🏖️", None),
    ("la fleur", "die Blume", "die", "A1", "🌸", "1490750967868-88aa4486c946"),
    ("l'arbre", "der Baum", "der", "A1", "🌳", "1441974231531-c6227db76b6e"),
    ("la feuille", "das Blatt", "das", "A2", "🍃", None),
    ("l'herbe", "das Gras", "das", "A2", "🌿", None),
    ("la plante", "die Pflanze", "die", "A2", "🪴", None),
    ("le printemps", "der Frühling", "der", "A1", "🌷", None),
    ("l'été", "der Sommer", "der", "A1", "☀️", None),
    ("l'automne", "der Herbst", "der", "A1", "🍂", None),
    ("l'hiver", "der Winter", "der", "A1", "⛄", None),
    ("le climat", "das Klima", "das", "B1", "🌡️", None),
    ("la météo", "das Wetter", "das", "A1", "🌤️", None),
    ("la tempête", "der Sturm", "der", "B1", "🌪️", None),

    # === LOISIRS ===
    ("le film", "der Film", "der", "A1", "🎬", None),
    ("la musique", "die Musik", "die", "A1", "🎵", None),
    ("le sport", "der Sport", "der", "A1", "⚽", None),
    ("le jeu", "das Spiel", "das", "A1", "🎮", None),
    ("la fête", "die Party", "die", "A1", "🎉", None),
    ("les vacances", "der Urlaub", "der", "A1", "🏖️", None),
    ("la photo", "das Foto", "das", "A1", "📸", None),
    ("le football", "der Fußball", "der", "A1", "⚽", None),
    ("le tennis", "das Tennis", "das", "A1", "🎾", None),
    ("la natation", "das Schwimmen", "das", "A2", "🏊", None),
    ("la danse", "der Tanz", "der", "A2", "💃", None),
    ("le théâtre", "das Theater", "das", "A1", "🎭", None),
    ("le musée", "das Museum", "das", "A1", "🏛️", None),
    ("le concert", "das Konzert", "das", "A1", "🎤", None),
    ("la guitare", "die Gitarre", "die", "A1", "🎸", None),
    ("le piano", "das Klavier", "das", "A1", "🎹", None),
    ("la chanson", "das Lied", "das", "A1", "🎶", None),
    ("le hobby", "das Hobby", "das", "A1", "🎨", None),
    ("la lecture", "das Lesen", "das", "A2", "📖", None),
    ("le voyage", "die Reise", "die", "A1", "✈️", None),

    # === ARGENT & ACHATS ===
    ("l'argent", "das Geld", "das", "A1", "💰", None),
    ("le prix", "der Preis", "der", "A1", "💲", None),
    ("le magasin", "das Geschäft", "das", "A1", "🛒", None),
    ("le marché", "der Markt", "der", "A1", "🛍️", None),
    ("le supermarché", "der Supermarkt", "der", "A1", "🏪", None),
    ("la banque", "die Bank", "die", "A1", "🏦", None),
    ("la carte", "die Karte", "die", "A1", "💳", None),
    ("le billet", "der Schein", "der", "A2", "💵", None),
    ("la monnaie", "das Kleingeld", "das", "A2", "🪙", None),
    ("l'euro", "der Euro", "der", "A1", "💶", None),
    ("le cadeau", "das Geschenk", "das", "A1", "🎁", None),
    ("la pharmacie", "die Apotheke", "die", "A1", "💊", None),
    ("la poste", "die Post", "die", "A1", "📮", None),
    ("l'hôpital", "das Krankenhaus", "das", "A1", "🏥", None),
    ("le médicament", "das Medikament", "das", "A2", "💊", None),
    ("la facture", "die Rechnung", "die", "A2", "🧾", None),
    ("le contrat", "der Vertrag", "der", "B1", "📜", None),
    ("la dette", "die Schulden", "die", "B1", "💸", None),
    ("l'économie", "die Wirtschaft", "die", "B1", "📈", None),
    ("l'impôt", "die Steuer", "die", "B1", "💰", None),
]

NOMS_NOUVEAUX = [
    # ============ FAMILLE & RELATIONS ÉLARGIES (15) ============
    ("le beau-père", "der Schwiegervater", "der", "B1", "👨", None),
    ("la belle-mère", "die Schwiegermutter", "die", "B1", "👩", None),
    ("le beau-frère", "der Schwager", "der", "B1", "👨", None),
    ("la belle-sœur", "die Schwägerin", "die", "B1", "👩", None),
    ("le petit-fils", "der Enkel", "der", "A2", "👶", None),
    ("la petite-fille", "die Enkelin", "die", "A2", "👧", None),
    ("le filleul", "das Patenkind", "das", "B2", "👶", None),
    ("l'orphelin", "das Waisenkind", "das", "B2", "👦", None),
    ("le veuf", "der Witwer", "der", "B2", "👴", None),
    ("la veuve", "die Witwe", "die", "B2", "👵", None),
    ("le célibataire", "der Junggeselle", "der", "B1", "🚶", None),
    ("l'ancêtre", "der Vorfahre", "der", "B2", "👴", None),
    ("le descendant", "der Nachkomme", "der", "B2", "👶", None),
    ("la fiancée", "die Verlobte", "die", "B1", "💍", None),
    ("le fiancé", "der Verlobte", "der", "B1", "💍", None),

    # ============ MÉTIERS ÉLARGIS (20) ============
    ("le pharmacien", "der Apotheker", "der", "A2", "💊", None),
    ("le dentiste", "der Zahnarzt", "der", "A2", "🦷", None),
    ("le vétérinaire", "der Tierarzt", "der", "B1", "🐕", None),
    ("le coiffeur", "der Friseur", "der", "A2", "✂️", None),
    ("le mécanicien", "der Mechaniker", "der", "A2", "🔧", None),
    ("l'électricien", "der Elektriker", "der", "B1", "⚡", None),
    ("le plombier", "der Klempner", "der", "B1", "🔧", None),
    ("l'architecte", "der Architekt", "der", "B1", "📐", None),
    ("le programmeur", "der Programmierer", "der", "B1", "💻", None),
    ("le scientifique", "der Wissenschaftler", "der", "B1", "🔬", None),
    ("le chercheur", "der Forscher", "der", "B2", "🔬", None),
    ("l'écrivain", "der Schriftsteller", "der", "B1", "✍️", None),
    ("le photographe", "der Fotograf", "der", "B1", "📷", None),
    ("le musicien", "der Musiker", "der", "A2", "🎵", None),
    ("l'acteur", "der Schauspieler", "der", "A2", "🎭", None),
    ("le facteur", "der Briefträger", "der", "B1", "📬", None),
    ("le jardinier", "der Gärtner", "der", "B1", "🌱", None),
    ("le maire", "der Bürgermeister", "der", "B1", "🏛️", None),
    ("le ministre", "der Minister", "der", "B2", "🏛️", None),
    ("l'entrepreneur", "der Unternehmer", "der", "B2", "💼", None),

    # ============ TECHNOLOGIE & MODERNITÉ (20) ============
    ("l'internet", "das Internet", "das", "A2", "🌐", None),
    ("le site web", "die Webseite", "die", "A2", "🌐", None),
    ("le mot de passe", "das Passwort", "das", "A2", "🔐", None),
    ("l'application", "die App", "die", "A2", "📱", None),
    ("l'écran", "der Bildschirm", "der", "A2", "🖥️", None),
    ("le clavier", "die Tastatur", "die", "A2", "⌨️", None),
    ("la souris", "die Maus", "die", "A2", "🖱️", None),
    ("le casque", "der Kopfhörer", "der", "A2", "🎧", None),
    ("la caméra", "die Kamera", "die", "A2", "📹", None),
    ("le fichier", "die Datei", "die", "B1", "📁", None),
    ("le dossier", "der Ordner", "der", "B1", "📂", None),
    ("le réseau", "das Netzwerk", "das", "B1", "🌐", None),
    ("le logiciel", "die Software", "die", "B1", "💾", None),
    ("le message", "die Nachricht", "die", "A1", "💬", None),
    ("le courriel", "die E-Mail", "die", "A1", "📧", None),
    ("le mot-clé", "das Stichwort", "das", "B2", "🔤", None),
    ("la donnée", "die Daten", "die", "B1", "📊", None),
    ("l'algorithme", "der Algorithmus", "der", "B2", "🤖", None),
    ("la batterie", "die Batterie", "die", "A2", "🔋", None),
    ("le chargeur", "das Ladegerät", "das", "B1", "🔌", None),

    # ============ VOYAGES & TOURISME (15) ============
    ("la destination", "das Ziel", "das", "B1", "🎯", None),
    ("l'itinéraire", "die Reiseroute", "die", "B2", "🗺️", None),
    ("le guide", "der Reiseführer", "der", "A2", "📖", None),
    ("la carte", "die Landkarte", "die", "A2", "🗺️", None),
    ("la frontière", "die Grenze", "die", "B1", "🚧", None),
    ("le douanier", "der Zollbeamte", "der", "B2", "🛂", None),
    ("le bagage", "das Gepäck", "das", "A2", "🧳", None),
    ("l'hôtel", "das Hotel", "das", "A1", "🏨", None),
    ("l'auberge", "die Herberge", "die", "B1", "🏠", None),
    ("la réception", "die Rezeption", "die", "B1", "🛎️", None),
    ("la chambre d'hôtel", "das Hotelzimmer", "das", "A2", "🛏️", None),
    ("le pays", "das Land", "das", "A1", "🌍", None),
    ("la ville", "die Stadt", "die", "A1", "🏙️", None),
    ("le village", "das Dorf", "das", "A2", "🏘️", None),
    ("la capitale", "die Hauptstadt", "die", "A2", "🏛️", None),

    # ============ SENTIMENTS & ÉMOTIONS (15) ============
    ("le bonheur", "das Glück", "das", "A2", "😊", None),
    ("la tristesse", "die Traurigkeit", "die", "B1", "😢", None),
    ("la peur", "die Angst", "die", "A2", "😨", None),
    ("la colère", "die Wut", "die", "B1", "😡", None),
    ("la joie", "die Freude", "die", "A2", "🥳", None),
    ("l'amour", "die Liebe", "die", "A1", "❤️", None),
    ("la haine", "der Hass", "der", "B1", "💔", None),
    ("l'espoir", "die Hoffnung", "die", "B1", "🌈", None),
    ("le rêve", "der Traum", "der", "A2", "💭", None),
    ("le cauchemar", "der Albtraum", "der", "B1", "😱", None),
    ("la surprise", "die Überraschung", "die", "A2", "😲", None),
    ("la jalousie", "die Eifersucht", "die", "B2", "💚", None),
    ("la honte", "die Scham", "die", "B2", "😳", None),
    ("la fierté", "der Stolz", "der", "B1", "🦚", None),
    ("le stress", "der Stress", "der", "A2", "😰", None),

    # ============ SANTÉ & MÉDECINE (15) ============
    ("la maladie", "die Krankheit", "die", "A2", "🤒", None),
    ("le rhume", "die Erkältung", "die", "A2", "🤧", None),
    ("la grippe", "die Grippe", "die", "A2", "🤒", None),
    ("la fièvre", "das Fieber", "das", "A2", "🌡️", None),
    ("la douleur", "der Schmerz", "der", "A2", "🤕", None),
    ("le mal de tête", "die Kopfschmerzen", "die", "A2", "🤕", None),
    ("la blessure", "die Verletzung", "die", "B1", "🩹", None),
    ("l'ordonnance", "das Rezept", "das", "B1", "📝", None),
    ("la consultation", "die Sprechstunde", "die", "B1", "🩺", None),
    ("la santé", "die Gesundheit", "die", "A2", "💪", None),
    ("l'allergie", "die Allergie", "die", "B1", "🤧", None),
    ("la vaccination", "die Impfung", "die", "B1", "💉", None),
    ("l'opération", "die Operation", "die", "B1", "🏥", None),
    ("le régime", "die Diät", "die", "B1", "🥗", None),
    ("la thérapie", "die Therapie", "die", "B2", "🧠", None),

    # ============ ÉDUCATION AVANCÉE (15) ============
    ("la conférence", "der Vortrag", "der", "B1", "🎤", None),
    ("le diplôme", "das Diplom", "das", "B1", "🎓", None),
    ("le doctorat", "die Doktorarbeit", "die", "B2", "🎓", None),
    ("la bibliothèque", "die Bibliothek", "die", "A1", "📚", None),
    ("la formation", "die Ausbildung", "die", "A2", "🎓", None),
    ("le stage", "das Praktikum", "das", "B1", "💼", None),
    ("la bourse", "das Stipendium", "das", "B2", "💰", None),
    ("la recherche", "die Forschung", "die", "B2", "🔬", None),
    ("la thèse", "die These", "die", "B2", "📜", None),
    ("la discipline", "das Fachgebiet", "das", "B2", "📚", None),
    ("la connaissance", "das Wissen", "das", "B1", "🧠", None),
    ("la compétence", "die Fähigkeit", "die", "B1", "💪", None),
    ("le talent", "das Talent", "das", "A2", "🌟", None),
    ("l'expérience", "die Erfahrung", "die", "A2", "💡", None),
    ("le savoir-faire", "das Know-how", "das", "B2", "💼", None),

    # ============ SOCIÉTÉ & POLITIQUE (15) ============
    ("la société", "die Gesellschaft", "die", "B1", "👥", None),
    ("le gouvernement", "die Regierung", "die", "B1", "🏛️", None),
    ("l'élection", "die Wahl", "die", "B1", "🗳️", None),
    ("le vote", "die Stimme", "die", "B1", "✋", None),
    ("le citoyen", "der Bürger", "der", "B1", "🧑", None),
    ("la nationalité", "die Staatsangehörigkeit", "die", "B1", "🆔", None),
    ("la loi", "das Gesetz", "das", "B1", "⚖️", None),
    ("le tribunal", "das Gericht", "das", "B1", "⚖️", None),
    ("la justice", "die Gerechtigkeit", "die", "B2", "⚖️", None),
    ("la liberté", "die Freiheit", "die", "B1", "🕊️", None),
    ("l'égalité", "die Gleichheit", "die", "B1", "⚖️", None),
    ("la démocratie", "die Demokratie", "die", "B1", "🗳️", None),
    ("la guerre", "der Krieg", "der", "B1", "⚔️", None),
    ("la paix", "der Frieden", "der", "B1", "🕊️", None),
    ("l'immigration", "die Einwanderung", "die", "B2", "🌍", None),

    # ============ ÉCOLOGIE & ENVIRONNEMENT (10) ============
    ("l'environnement", "die Umwelt", "die", "B1", "🌍", None),
    ("la pollution", "die Verschmutzung", "die", "B1", "🏭", None),
    ("le recyclage", "das Recycling", "das", "B1", "♻️", None),
    ("les déchets", "der Müll", "der", "A2", "🗑️", None),
    ("le changement climatique", "der Klimawandel", "der", "B2", "🌡️", None),
    ("l'énergie", "die Energie", "die", "A2", "⚡", None),
    ("le solaire", "die Sonnenenergie", "die", "B1", "☀️", None),
    ("la nature", "die Natur", "die", "A1", "🌿", None),
    ("l'espèce", "die Art", "die", "B1", "🦋", None),
    ("la biodiversité", "die Artenvielfalt", "die", "B2", "🌳", None),

    # ============ DIVERS UTILES (10) ============
    ("l'idée", "die Idee", "die", "A1", "💡", None),
    ("la pensée", "der Gedanke", "der", "A2", "💭", None),
    ("la question", "die Frage", "die", "A1", "❓", None),
    ("la réponse", "die Antwort", "die", "A1", "💬", None),
    ("le problème", "das Problem", "das", "A1", "⚠️", None),
    ("la solution", "die Lösung", "die", "A2", "💡", None),
    ("le doute", "der Zweifel", "der", "B1", "🤔", None),
    ("le secret", "das Geheimnis", "das", "A2", "🤫", None),
    ("le mensonge", "die Lüge", "die", "B1", "🤥", None),
    ("la vérité", "die Wahrheit", "die", "A2", "✅", None),

    # ============ ÉVÉNEMENTS DE VIE (10) ============
    ("la naissance", "die Geburt", "die", "A2", "👶", None),
    ("l'anniversaire", "der Geburtstag", "der", "A1", "🎂", None),
    ("le mariage", "die Hochzeit", "die", "A2", "💒", None),
    ("le divorce", "die Scheidung", "die", "B1", "💔", None),
    ("la mort", "der Tod", "der", "A2", "⚰️", None),
    ("l'enterrement", "die Beerdigung", "die", "B1", "🕊️", None),
    ("la cérémonie", "die Zeremonie", "die", "B1", "🎩", None),
    ("la tradition", "die Tradition", "die", "A2", "🎎", None),
    ("la coutume", "die Sitte", "die", "B1", "🎭", None),
    ("la culture", "die Kultur", "die", "A2", "🎨", None),
]

# ============================================================
# VERBES — Ajout de 106 nouveaux verbes (212 → 318)
# Focus : verbes pronominaux, verbes à régime, verbes courants A2-B2
# ============================================================
VERBES_EXISTANTS = [
    ("être", "sein", "A1", "📌", None),
    ("avoir", "haben", "A1", "🤲", None),
    ("devenir", "werden", "A1", "🔄", None),
    ("pouvoir", "können", "A1", "💪", None),
    ("devoir", "müssen", "A1", "❗", None),
    ("vouloir", "wollen", "A1", "🎯", None),
    ("savoir", "wissen", "A1", "🧠", None),
    ("falloir", "sollen", "A1", "📋", None),
    ("avoir le droit", "dürfen", "A2", "✅", None),
    ("aimer (modal)", "mögen", "A1", "❤️", None),
    ("aller", "gehen", "A1", "🚶", "1476480862126-209bfaa8edc8"),
    ("venir", "kommen", "A1", "👋", None),
    ("être debout", "stehen", "A1", "🧍", None),
    ("être assis", "sitzen", "A1", "💺", None),
    ("être allongé", "liegen", "A1", "🛏️", None),
    ("courir", "laufen", "A1", "🏃", "1571008887538-b36bb32f4571"),
    ("conduire", "fahren", "A1", "🚗", None),
    ("voler", "fliegen", "A1", "🛫", None),
    ("nager", "schwimmen", "A1", "🏊", "1530549387789-4c1017266635"),
    ("danser", "tanzen", "A1", "💃", "1535525153412-5a42439a210d"),
    ("sauter", "springen", "A2", "🦘", None),
    ("tomber", "fallen", "A2", "🤸", None),
    ("monter", "steigen", "A2", "📈", None),
    ("descendre", "sinken", "B1", "📉", None),
    ("revenir", "zurückkommen", "A2", "↩️", None),
    ("partir", "abfahren", "A2", "🚂", None),
    ("arriver", "ankommen", "A1", "🛬", None),
    ("entrer", "eintreten", "A2", "🚪", None),
    ("sortir", "ausgehen", "A2", "🚪", None),
    ("passer", "vorbeigehen", "A2", "➡️", None),
    ("traverser", "überqueren", "B1", "🦓", None),
    ("se promener", "spazieren", "A2", "🚶", None),
    ("voyager", "reisen", "A1", "✈️", None),
    ("conduire", "fahren", "A1", "🚙", None),
    ("rouler", "rollen", "A2", "🎳", None),
    ("grimper", "klettern", "B1", "🧗", None),
    ("rentrer", "heimgehen", "A1", "🏠", None),
    ("manger", "essen", "A1", "🍽️", "1414235077428-338989a2e8c0"),
    ("boire", "trinken", "A1", "🥤", "1437418747212-8d9709afab22"),
    ("dormir", "schlafen", "A1", "😴", "1520206183501-b80df61043c2"),
    ("se réveiller", "aufwachen", "A1", "⏰", None),
    ("se lever", "aufstehen", "A1", "🛌", None),
    ("se laver", "sich waschen", "A1", "🚿", None),
    ("se doucher", "duschen", "A1", "🚿", None),
    ("se brosser", "putzen", "A1", "🪥", None),
    ("s'habiller", "sich anziehen", "A1", "👕", None),
    ("se déshabiller", "sich ausziehen", "A2", "👔", None),
    ("prendre le petit-déj", "frühstücken", "A1", "🥐", None),
    ("déjeuner", "mittagessen", "A1", "🍽️", None),
    ("dîner", "abendessen", "A1", "🍽️", None),
    ("cuisiner", "kochen", "A1", "🍳", "1556909114-f6e7ad7d3136"),
    ("faire les courses", "einkaufen", "A1", "🛒", "1483985988355-763728e1935b"),
    ("nettoyer", "putzen", "A2", "🧹", None),
    ("laver", "waschen", "A1", "🧺", None),
    ("repasser", "bügeln", "B1", "🔥", None),
    ("se reposer", "sich ausruhen", "A2", "💤", None),
    ("se coucher", "ins Bett gehen", "A1", "🛏️", None),
    ("ranger", "aufräumen", "A2", "📚", None),
    ("balayer", "fegen", "B1", "🧹", None),
    ("parler", "sprechen", "A1", "💬", "1573497019940-1c28c88b4f3e"),
    ("dire", "sagen", "A1", "💬", None),
    ("écouter", "hören", "A1", "🎧", "1505740420928-5e560c06d30e"),
    ("lire", "lesen", "A1", "📖", "1506880018603-83d5b814b5a6"),
    ("écrire", "schreiben", "A1", "✍️", "1455390582262-044cdead277a"),
    ("répondre", "antworten", "A1", "💬", None),
    ("demander", "fragen", "A1", "❓", None),
    ("expliquer", "erklären", "A2", "💡", None),
    ("comprendre", "verstehen", "A1", "💡", None),
    ("traduire", "übersetzen", "A2", "🌐", None),
    ("téléphoner", "telefonieren", "A1", "📞", None),
    ("crier", "schreien", "B1", "📢", None),
    ("chuchoter", "flüstern", "B2", "🤫", None),
    ("discuter", "diskutieren", "A2", "💬", None),
    ("raconter", "erzählen", "A2", "📖", None),
    ("appeler", "anrufen", "A1", "📞", None),
    ("envoyer", "schicken", "A1", "📨", None),
    ("recevoir", "bekommen", "A1", "📦", None),
    ("penser", "denken", "A1", "💭", None),
    ("savoir", "wissen", "A1", "🧠", None),
    ("connaître", "kennen", "A1", "👋", None),
    ("apprendre", "lernen", "A1", "📚", "1456513080510-7bf3a84b82f8"),
    ("étudier", "studieren", "A1", "🎓", None),
    ("oublier", "vergessen", "A1", "🤔", None),
    ("se souvenir", "sich erinnern", "A2", "💭", None),
    ("rêver", "träumen", "A2", "💤", None),
    ("croire", "glauben", "A1", "🙏", None),
    ("penser que", "meinen", "A2", "💬", None),
    ("espérer", "hoffen", "A2", "🌈", None),
    ("souhaiter", "wünschen", "A2", "🌠", None),
    ("avoir besoin", "brauchen", "A1", "🆘", None),
    ("chercher", "suchen", "A1", "🔍", "1504711434969-e33886168f5c"),
    ("trouver", "finden", "A1", "🎯", "1521295121783-8a321d551ad2"),
    ("perdre", "verlieren", "A2", "❌", None),
    ("essayer", "versuchen", "A2", "🎯", None),
    ("réussir", "schaffen", "A2", "🏆", None),
    ("décider", "entscheiden", "B1", "🎯", None),
    ("choisir", "wählen", "A2", "👆", None),
    ("comparer", "vergleichen", "B1", "⚖️", None),
    ("analyser", "analysieren", "B2", "🔬", None),
    ("imaginer", "sich vorstellen", "B1", "💭", None),
    ("se concentrer", "sich konzentrieren", "B1", "🎯", None),
    ("aimer", "lieben", "A1", "❤️", "1518621736915-f3b1c41bfd00"),
    ("détester", "hassen", "A2", "💔", "1541199249251-f713e6145474"),
    ("plaire", "gefallen", "A1", "😊", None),
    ("se réjouir", "sich freuen", "A1", "🎉", None),
    ("s'énerver", "sich ärgern", "B1", "😤", None),
    ("pleurer", "weinen", "A1", "😢", "1503454537195-1dcabb73ffb9"),
    ("rire", "lachen", "A1", "😄", "1542596594-649edbc13630"),
    ("sourire", "lächeln", "A2", "😊", None),
    ("ressentir", "fühlen", "B1", "💗", None),
    ("souffrir", "leiden", "B1", "😣", None),
    ("avoir peur", "Angst haben", "A2", "😨", None),
    ("être surpris", "überrascht sein", "B1", "😲", None),
    ("être déçu", "enttäuscht sein", "B1", "😞", None),
    ("être fâché", "wütend sein", "A2", "😡", None),
    ("être heureux", "glücklich sein", "A1", "😄", None),
    ("être triste", "traurig sein", "A1", "😢", None),
    ("travailler", "arbeiten", "A1", "💼", "1497032628192-86f99bcd76bc"),
    ("enseigner", "lehren", "A2", "👨‍🏫", "1524178232363-1fb2b075b655"),
    ("expliquer", "erklären", "A2", "💡", None),
    ("présenter", "präsentieren", "B1", "📊", None),
    ("organiser", "organisieren", "B1", "📋", None),
    ("planifier", "planen", "B1", "📅", None),
    ("préparer", "vorbereiten", "A2", "📋", None),
    ("aider", "helfen", "A1", "🤝", None),
    ("collaborer", "zusammenarbeiten", "B1", "👥", None),
    ("diriger", "leiten", "B1", "👔", None),
    ("contrôler", "kontrollieren", "B1", "✅", None),
    ("corriger", "korrigieren", "B1", "✏️", None),
    ("réviser", "überprüfen", "B1", "🔍", None),
    ("jouer", "spielen", "A1", "🎮", "1511512578047-dfb367046420"),
    ("chanter", "singen", "A1", "🎤", "1516280440614-37939bbacd81"),
    ("écouter de la musique", "Musik hören", "A1", "🎵", None),
    ("regarder", "schauen", "A1", "👀", None),
    ("voir", "sehen", "A1", "👁️", "1494869042583-f6c911f04b4c"),
    ("dessiner", "zeichnen", "A2", "🎨", None),
    ("peindre", "malen", "A2", "🖌️", None),
    ("photographier", "fotografieren", "A2", "📸", None),
    ("faire du sport", "Sport machen", "A1", "⚽", None),
    ("courir", "rennen", "A2", "🏃", None),
    ("faire du vélo", "Rad fahren", "A1", "🚴", None),
    ("voyager", "reisen", "A1", "🧳", None),
    ("visiter", "besichtigen", "A2", "🏛️", None),
    ("fêter", "feiern", "A1", "🎉", None),
    ("inviter", "einladen", "A2", "✉️", None),
    ("rencontrer", "treffen", "A1", "🤝", None),
    ("acheter", "kaufen", "A1", "🛒", None),
    ("vendre", "verkaufen", "A2", "💰", "1556742111-a301076d9d18"),
    ("payer", "zahlen", "A1", "💳", None),
    ("coûter", "kosten", "A1", "💲", None),
    ("dépenser", "ausgeben", "B1", "💸", None),
    ("économiser", "sparen", "B1", "🏦", None),
    ("emprunter", "leihen", "B1", "🤲", None),
    ("rendre", "zurückgeben", "A2", "↩️", None),
    ("offrir", "schenken", "A2", "🎁", None),
    ("commander", "bestellen", "A2", "📋", None),
    ("livrer", "liefern", "B1", "📦", None),
    ("échanger", "tauschen", "B1", "🔄", None),
    ("réserver", "reservieren", "A2", "📅", None),
    ("ouvrir", "öffnen", "A1", "🔓", "1516455590571-18256e5bb9ff"),
    ("fermer", "schließen", "A1", "🔒", "1582139329536-e7284fece509"),
    ("commencer", "beginnen", "A1", "▶️", "1533228876829-65c94e7b5025"),
    ("finir", "beenden", "A1", "🏁", "1533236897111-3e94666b2edf"),
    ("continuer", "weitermachen", "A2", "➡️", None),
    ("arrêter", "aufhören", "A1", "🛑", None),
    ("attendre", "warten", "A1", "⏰", None),
    ("donner", "geben", "A1", "🤲", None),
    ("prendre", "nehmen", "A1", "✋", None),
    ("porter", "tragen", "A1", "🎒", None),
    ("mettre", "legen", "A1", "📍", None),
    ("poser", "stellen", "A2", "📍", None),
    ("tenir", "halten", "A2", "✊", None),
    ("toucher", "berühren", "B1", "👆", None),
    ("frapper", "klopfen", "B1", "✊", None),
    ("pousser", "drücken", "A2", "👉", None),
    ("tirer", "ziehen", "A2", "👈", None),
    ("lancer", "werfen", "A2", "🎯", None),
    ("attraper", "fangen", "B1", "✋", None),
    ("casser", "kaputt machen", "A2", "💥", None),
    ("réparer", "reparieren", "A2", "🔧", None),
    ("construire", "bauen", "A2", "🏗️", None),
    ("détruire", "zerstören", "B1", "💥", None),
    ("créer", "schaffen", "B1", "✨", None),
    ("changer", "ändern", "A2", "🔄", None),
    ("améliorer", "verbessern", "B1", "📈", None),
    ("rester", "bleiben", "A1", "📍", None),
    ("partir", "weggehen", "A2", "👋", None),
    ("rentrer", "nach Hause gehen", "A1", "🏠", None),
    ("aider", "helfen", "A1", "🤝", None),
    ("montrer", "zeigen", "A1", "👉", None),
    ("expliquer", "erklären", "A2", "💡", None),
    ("comprendre", "verstehen", "A1", "💡", None),
    ("oublier", "vergessen", "A1", "🤷", None),
    ("se rappeler", "sich erinnern", "A2", "💭", None),
    ("remercier", "danken", "A1", "🙏", None),
    ("excuser", "entschuldigen", "A1", "🙇", None),
    ("féliciter", "gratulieren", "A2", "🎉", None),
    ("inviter", "einladen", "A2", "✉️", None),
    ("accepter", "annehmen", "A2", "✅", None),
    ("refuser", "ablehnen", "B1", "❌", None),
    ("promettre", "versprechen", "B1", "🤞", None),
    ("mentir", "lügen", "B1", "🤥", None),
    ("croire", "glauben", "A1", "🙏", None),
    ("douter", "zweifeln", "B1", "🤔", None),
    ("confirmer", "bestätigen", "B1", "✅", None),
    ("être malade", "krank sein", "A2", "🤒", None),
    ("guérir", "gesund werden", "B1", "💊", None),
    ("blesser", "verletzen", "B1", "🩹", None),
    ("souffrir", "leiden", "B1", "😣", None),
    ("respirer", "atmen", "A2", "🫁", None),
    ("se sentir", "sich fühlen", "A2", "💗", None),
    ("aller mieux", "besser werden", "A2", "📈", None),
]

VERBES_NOUVEAUX = [
    # ============ VERBES PRONOMINAUX (25) ============
    ("se reposer", "sich erholen", "B1", "💆", None),
    ("se dépêcher", "sich beeilen", "A2", "⏰", None),
    ("s'occuper", "sich kümmern", "B1", "🤲", None),
    ("se rappeler", "sich merken", "A2", "💭", None),
    ("s'intéresser", "sich interessieren", "A2", "💡", None),
    ("se préparer", "sich vorbereiten", "A2", "📋", None),
    ("s'asseoir", "sich setzen", "A1", "💺", None),
    ("se coucher", "sich hinlegen", "A2", "🛏️", None),
    ("se plaindre", "sich beschweren", "B1", "😤", None),
    ("s'excuser", "sich entschuldigen", "A2", "🙇", None),
    ("se présenter", "sich vorstellen", "A2", "👋", None),
    ("se marier", "sich verheiraten", "B1", "💍", None),
    ("se disputer", "sich streiten", "B1", "🗣️", None),
    ("se réconcilier", "sich versöhnen", "B2", "🤝", None),
    ("se moquer", "sich lustig machen", "B2", "😆", None),
    ("se fatiguer", "sich anstrengen", "B1", "💪", None),
    ("se détendre", "sich entspannen", "A2", "💆", None),
    ("se baigner", "sich baden", "A2", "🛁", None),
    ("se brosser les dents", "sich die Zähne putzen", "A1", "🪥", None),
    ("se peigner", "sich kämmen", "A2", "💇", None),
    ("se raser", "sich rasieren", "A2", "🪒", None),
    ("se maquiller", "sich schminken", "B1", "💄", None),
    ("s'habituer", "sich gewöhnen", "B1", "🔄", None),
    ("s'inquiéter", "sich sorgen", "B1", "😟", None),
    ("se sentir bien", "sich wohlfühlen", "A2", "😊", None),

    # ============ VERBES À RÉGIME (avec préposition) (25) ============
    ("attendre (qch)", "warten auf", "A2", "⏰", None),
    ("penser à", "denken an", "A2", "💭", None),
    ("croire en", "glauben an", "B1", "🙏", None),
    ("dépendre de", "abhängen von", "B1", "🔗", None),
    ("parler de", "sprechen über", "A2", "💬", None),
    ("s'inquiéter de", "sich sorgen um", "B1", "😟", None),
    ("se réjouir de", "sich freuen über", "A2", "🎉", None),
    ("se plaindre de", "sich beschweren über", "B1", "😤", None),
    ("rêver de", "träumen von", "A2", "💭", None),
    ("avoir besoin de", "brauchen", "A1", "🆘", None),
    ("se souvenir de", "sich erinnern an", "A2", "💭", None),
    ("s'intéresser à", "sich interessieren für", "A2", "💡", None),
    ("s'occuper de", "sich kümmern um", "B1", "🤲", None),
    ("réfléchir à", "nachdenken über", "B1", "💭", None),
    ("compter sur", "zählen auf", "B1", "🔢", None),
    ("se moquer de", "sich lustig machen über", "B2", "😆", None),
    ("avoir peur de", "Angst haben vor", "A2", "😨", None),
    ("féliciter pour", "gratulieren zu", "A2", "🎉", None),
    ("remercier pour", "danken für", "A1", "🙏", None),
    ("croire à", "glauben an", "B1", "🙏", None),
    ("vivre de", "leben von", "B1", "🍞", None),
    ("réagir à", "reagieren auf", "B1", "💥", None),
    ("renoncer à", "verzichten auf", "B2", "🚫", None),
    ("se concentrer sur", "sich konzentrieren auf", "B1", "🎯", None),
    ("se spécialiser en", "sich spezialisieren auf", "B2", "📚", None),

    # ============ VERBES COURANTS A2-B1 (30) ============
    ("durer", "dauern", "A2", "⏳", None),
    ("appartenir", "gehören", "A2", "🔑", None),
    ("se passer", "passieren", "A2", "💥", None),
    ("se produire", "geschehen", "B1", "💥", None),
    ("arriver (qch)", "geschehen", "B1", "💥", None),
    ("se trouver", "sich befinden", "B1", "📍", None),
    ("exister", "existieren", "B1", "✨", None),
    ("vivre", "leben", "A1", "💗", None),
    ("habiter", "wohnen", "A1", "🏠", None),
    ("naître", "geboren werden", "A2", "👶", None),
    ("mourir", "sterben", "A2", "💀", None),
    ("grandir", "wachsen", "A2", "📈", None),
    ("vieillir", "altern", "B1", "👴", None),
    ("changer (qch)", "verändern", "B1", "🔄", None),
    ("différer", "sich unterscheiden", "B2", "↔️", None),
    ("ressembler", "ähneln", "B1", "👯", None),
    ("contenir", "enthalten", "B1", "📦", None),
    ("inclure", "einschließen", "B2", "➕", None),
    ("exclure", "ausschließen", "B2", "➖", None),
    ("ajouter", "hinzufügen", "B1", "➕", None),
    ("supprimer", "löschen", "B1", "🗑️", None),
    ("remplacer", "ersetzen", "B1", "🔄", None),
    ("éviter", "vermeiden", "B1", "🚫", None),
    ("permettre", "erlauben", "A2", "✅", None),
    ("interdire", "verbieten", "B1", "❌", None),
    ("obliger", "zwingen", "B2", "❗", None),
    ("conseiller", "raten", "B1", "💡", None),
    ("recommander", "empfehlen", "A2", "👍", None),
    ("avertir", "warnen", "B1", "⚠️", None),
    ("informer", "informieren", "B1", "ℹ️", None),

    # ============ VERBES B2 - LANGAGE SOUTENU (15) ============
    ("réaliser", "verwirklichen", "B2", "✨", None),
    ("constater", "feststellen", "B2", "🔍", None),
    ("considérer", "betrachten", "B2", "👁️", None),
    ("supposer", "vermuten", "B2", "🤔", None),
    ("prouver", "beweisen", "B2", "✅", None),
    ("démontrer", "darlegen", "B2", "📊", None),
    ("souligner", "betonen", "B2", "✏️", None),
    ("préciser", "präzisieren", "B2", "🎯", None),
    ("résumer", "zusammenfassen", "B2", "📝", None),
    ("développer", "entwickeln", "B1", "🌱", None),
    ("approfondir", "vertiefen", "B2", "🔬", None),
    ("contredire", "widersprechen", "B2", "🗣️", None),
    ("convaincre", "überzeugen", "B1", "💡", None),
    ("influencer", "beeinflussen", "B2", "🌊", None),
    ("transformer", "verwandeln", "B2", "✨", None),

    # ============ VERBES DE PERCEPTION & SENSATION (11) ============
    ("sentir", "riechen", "A2", "👃", None),
    ("goûter", "schmecken", "A2", "👅", None),
    ("ressentir", "empfinden", "B2", "💗", None),
    ("percevoir", "wahrnehmen", "B2", "👁️", None),
    ("observer", "beobachten", "B1", "👀", None),
    ("remarquer", "bemerken", "A2", "👁️", None),
    ("découvrir", "entdecken", "A2", "🔍", None),
    ("révéler", "enthüllen", "B2", "🎭", None),
    ("cacher", "verstecken", "A2", "🙈", None),
    ("se cacher", "sich verstecken", "A2", "🙈", None),
    ("apparaître", "erscheinen", "B1", "✨", None),
]

# ============================================================
# ADJECTIFS — Ajout de 76 nouveaux (152 → 228)
# ============================================================
ADJECTIFS_EXISTANTS = [
    ("grand", "groß", "A1", "📏", "1486325212027-8081e485255e"),
    ("petit", "klein", "A1", "🔬", "1530281700549-e82e7bf110d6"),
    ("long", "lang", "A1", "📐", "1517483000871-1dbf64a6e1c6"),
    ("court", "kurz", "A1", "📏", "1606107557195-0e29a4b5b4aa"),
    ("haut", "hoch", "A1", "🏔️", None),
    ("bas", "niedrig", "A2", "⬇️", None),
    ("large", "breit", "A2", "↔️", "1519681393784-d120267933ba"),
    ("étroit", "schmal", "B1", "↕️", "1499002238440-d264edd596ec"),
    ("épais", "dick", "A2", "📚", None),
    ("mince", "dünn", "A2", "🦴", None),
    ("gros", "dick", "A1", "🐘", None),
    ("plein", "voll", "A1", "🌕", "1556881124-1c1a8d8fa1dc"),
    ("vide", "leer", "A1", "⚪", "1505761671935-60b3a7427bad"),
    ("nombreux", "viele", "A2", "👥", None),
    ("peu", "wenig", "A1", "🤏", None),
    ("beaucoup", "viel", "A1", "📈", None),
    ("bon", "gut", "A1", "👍", "1517232115160-ff93364542dd"),
    ("mauvais", "schlecht", "A1", "👎", "1453728013993-6d66e9c9123a"),
    ("beau", "schön", "A1", "✨", "1493612276216-ee3925520721"),
    ("laid", "hässlich", "A2", "😖", None),
    ("joli", "hübsch", "A2", "🌸", None),
    ("intéressant", "interessant", "A1", "💡", None),
    ("ennuyeux", "langweilig", "A2", "😴", None),
    ("amusant", "lustig", "A1", "😄", None),
    ("drôle", "witzig", "A2", "🤣", None),
    ("sérieux", "ernst", "A2", "🧐", None),
    ("important", "wichtig", "A1", "❗", None),
    ("inutile", "unnötig", "B1", "🚫", None),
    ("excellent", "ausgezeichnet", "B1", "🌟", None),
    ("parfait", "perfekt", "A2", "💯", None),
    ("génial", "toll", "A1", "🤩", None),
    ("super", "super", "A1", "✨", None),
    ("formidable", "wunderbar", "A2", "🎉", None),
    ("rapide", "schnell", "A1", "⚡", "1492144534655-ae79c964c9d7"),
    ("lent", "langsam", "A1", "🐌", "1559827260-dc66d52bef19"),
    ("nouveau", "neu", "A1", "🆕", "1513151233558-d860c5398176"),
    ("vieux", "alt", "A1", "👴", "1559548331-f9cb98280344"),
    ("jeune", "jung", "A1", "👶", None),
    ("récent", "neulich", "B1", "🆕", None),
    ("ancien", "ehemalig", "B1", "📜", None),
    ("moderne", "modern", "A2", "💻", None),
    ("traditionnel", "traditionell", "B1", "🏛️", None),
    ("chaud", "heiß", "A1", "🔥", "1494059980473-813e73ee784b"),
    ("froid", "kalt", "A1", "❄️", "1457269449834-928af64c684d"),
    ("tiède", "warm", "A2", "🌡️", None),
    ("frais", "kühl", "A2", "🍃", None),
    ("ensoleillé", "sonnig", "A2", "☀️", None),
    ("nuageux", "wolkig", "A2", "☁️", None),
    ("pluvieux", "regnerisch", "B1", "🌧️", None),
    ("sec", "trocken", "A2", "🏜️", None),
    ("humide", "feucht", "B1", "💧", None),
    ("mouillé", "nass", "A2", "💦", None),
    ("heureux", "glücklich", "A1", "😊", "1496360166961-10a51d5f367a"),
    ("triste", "traurig", "A1", "😔", "1499209974431-9dddcece7f88"),
    ("content", "zufrieden", "A2", "😌", None),
    ("mécontent", "unzufrieden", "B1", "😒", None),
    ("fâché", "wütend", "A2", "😡", None),
    ("calme", "ruhig", "A2", "😌", None),
    ("nerveux", "nervös", "A2", "😰", None),
    ("inquiet", "besorgt", "B1", "😟", None),
    ("fier", "stolz", "B1", "🦚", None),
    ("amoureux", "verliebt", "B1", "😍", None),
    ("jaloux", "eifersüchtig", "B1", "💚", None),
    ("seul", "allein", "A1", "🚶", None),
    ("ensemble", "zusammen", "A2", "👫", None),
    ("fatigué", "müde", "A1", "😴", None),
    ("énergique", "energiegeladen", "B1", "⚡", None),
    ("facile", "einfach", "A1", "✅", "1503676260728-1c00da094a0b"),
    ("difficile", "schwer", "A1", "⚠️", "1551836022-d5d88e9218df"),
    ("compliqué", "kompliziert", "B1", "🌀", None),
    ("simple", "einfach", "A1", "✨", None),
    ("clair", "klar", "A2", "💡", None),
    ("confus", "verwirrt", "B1", "😵", None),
    ("fort", "stark", "A1", "💪", "1534438327276-14e5300c3a48"),
    ("faible", "schwach", "A2", "🤕", "1551845041-63e8e76836ea"),
    ("sain", "gesund", "A2", "🥗", None),
    ("malade", "krank", "A1", "🤒", None),
    ("propre", "sauber", "A2", "🧼", "1583947215259-38e31be8751f"),
    ("sale", "schmutzig", "A2", "🦠", "1581578017093-cd30fce4eeb7"),
    ("riche", "reich", "A2", "💎", "1543699565-003b8adda5fc"),
    ("pauvre", "arm", "A2", "🪙", "1532629345422-7515f3d16bb6"),
    ("cher", "teuer", "A1", "💸", None),
    ("bon marché", "billig", "A2", "💰", None),
    ("gratuit", "kostenlos", "A2", "🆓", None),
    ("intelligent", "klug", "A2", "🧠", "1507413245164-6160d8298b31"),
    ("stupide", "dumm", "A2", "🤪", "1521120098171-d56a877a3cc6"),
    ("sage", "weise", "B1", "🦉", None),
    ("gentil", "nett", "A1", "😊", None),
    ("méchant", "böse", "A2", "😈", None),
    ("aimable", "freundlich", "A1", "🤗", None),
    ("poli", "höflich", "A2", "🎩", None),
    ("impoli", "unhöflich", "B1", "😠", None),
    ("honnête", "ehrlich", "B1", "🤝", None),
    ("courageux", "mutig", "B1", "🦁", None),
    ("timide", "schüchtern", "B1", "🙈", None),
    ("généreux", "großzügig", "B1", "🤲", None),
    ("égoïste", "egoistisch", "B1", "🪞", None),
    ("patient", "geduldig", "B1", "⏳", None),
    ("paresseux", "faul", "A2", "😪", None),
    ("travailleur", "fleißig", "A2", "💼", None),
    ("créatif", "kreativ", "B1", "🎨", None),
    ("rouge", "rot", "A1", "🔴", None),
    ("bleu", "blau", "A1", "🔵", None),
    ("vert", "grün", "A1", "🟢", None),
    ("jaune", "gelb", "A1", "🟡", None),
    ("noir", "schwarz", "A1", "⚫", None),
    ("blanc", "weiß", "A1", "⚪", None),
    ("gris", "grau", "A1", "🌫️", None),
    ("brun", "braun", "A1", "🟤", None),
    ("orange", "orange", "A1", "🟠", None),
    ("rose", "rosa", "A1", "🌸", None),
    ("violet", "lila", "A2", "🟣", None),
    ("clair", "hell", "A2", "💡", None),
    ("foncé", "dunkel", "A2", "🌑", None),
    ("sucré", "süß", "A1", "🍬", None),
    ("salé", "salzig", "A2", "🧂", None),
    ("acide", "sauer", "A2", "🍋", None),
    ("amer", "bitter", "B1", "☕", None),
    ("épicé", "scharf", "A2", "🌶️", None),
    ("délicieux", "lecker", "A1", "😋", None),
    ("dégoûtant", "ekelhaft", "B1", "🤢", None),
    ("vrai", "wahr", "A2", "✅", None),
    ("faux", "falsch", "A1", "❌", None),
    ("possible", "möglich", "A2", "🤔", None),
    ("impossible", "unmöglich", "A2", "🚫", None),
    ("nécessaire", "nötig", "B1", "❗", None),
    ("différent", "anders", "A1", "🔀", None),
    ("pareil", "gleich", "A1", "🟰", None),
    ("ouvert", "offen", "A1", "🔓", None),
    ("fermé", "geschlossen", "A1", "🔒", None),
    ("disponible", "verfügbar", "B1", "✅", None),
    ("occupé", "beschäftigt", "A2", "📞", None),
    ("libre", "frei", "A1", "🕊️", None),
    ("plein", "voll", "A1", "🥛", None),
    ("dangereux", "gefährlich", "A2", "⚠️", None),
    ("sûr", "sicher", "A2", "🛡️", None),
    ("célèbre", "berühmt", "A2", "⭐", None),
    ("inconnu", "unbekannt", "B1", "❓", None),
    ("typique", "typisch", "B1", "🎯", None),
    ("normal", "normal", "A2", "👌", None),
    ("étrange", "seltsam", "B1", "🤨", None),
    ("habituel", "gewöhnlich", "B1", "🔄", None),
    ("rare", "selten", "B1", "💎", None),
    ("commun", "häufig", "B1", "📊", None),
    ("absent", "abwesend", "B1", "🚪", None),
    ("présent", "anwesend", "A2", "✋", None),
    ("vivant", "lebendig", "B1", "💗", None),
    ("mort", "tot", "A2", "💀", None),
    ("célibataire", "ledig", "A2", "🚶", None),
    ("marié", "verheiratet", "A2", "💍", None),
    ("divorcé", "geschieden", "B1", "💔", None),
    ("nouveau", "neu", "A1", "🆕", None),
]

ADJECTIFS_NOUVEAUX = [
    # ============ EMOTIONS NUANCÉES (15) ============
    ("anxieux", "ängstlich", "B1", "😰", None),
    ("détendu", "entspannt", "A2", "😌", None),
    ("optimiste", "optimistisch", "B1", "🌈", None),
    ("pessimiste", "pessimistisch", "B1", "🌧️", None),
    ("enthousiaste", "begeistert", "B1", "🎉", None),
    ("déprimé", "deprimiert", "B1", "😞", None),
    ("frustré", "frustriert", "B1", "😤", None),
    ("satisfait", "befriedigt", "B1", "😊", None),
    ("ému", "gerührt", "B2", "🥺", None),
    ("indifférent", "gleichgültig", "B2", "🤷", None),
    ("passionné", "leidenschaftlich", "B1", "🔥", None),
    ("désespéré", "verzweifelt", "B2", "😩", None),
    ("rassuré", "beruhigt", "B1", "😌", None),
    ("ravi", "begeistert", "B1", "😄", None),
    ("perplexe", "ratlos", "B2", "🤔", None),

    # ============ CARACTÈRE (15) ============
    ("ambitieux", "ehrgeizig", "B1", "🎯", None),
    ("modeste", "bescheiden", "B1", "🙏", None),
    ("arrogant", "arrogant", "B1", "😤", None),
    ("sincère", "aufrichtig", "B1", "❤️", None),
    ("hypocrite", "scheinheilig", "B2", "🎭", None),
    ("fidèle", "treu", "B1", "🤝", None),
    ("loyal", "loyal", "B1", "🛡️", None),
    ("curieux", "neugierig", "A2", "🔍", None),
    ("attentif", "aufmerksam", "B1", "👀", None),
    ("distrait", "zerstreut", "B1", "🤯", None),
    ("dynamique", "dynamisch", "B1", "⚡", None),
    ("calme", "gelassen", "A2", "🧘", None),
    ("impulsif", "impulsiv", "B2", "💥", None),
    ("réfléchi", "überlegt", "B2", "🤔", None),
    ("indépendant", "unabhängig", "B1", "🕊️", None),

    # ============ PHYSIQUE & APPARENCE (12) ============
    ("élégant", "elegant", "B1", "👗", None),
    ("attirant", "attraktiv", "B1", "✨", None),
    ("séduisant", "verführerisch", "B2", "💋", None),
    ("athlétique", "sportlich", "B1", "💪", None),
    ("musclé", "muskulös", "B1", "💪", None),
    ("svelte", "schlank", "B1", "🧍", None),
    ("rond", "rund", "A2", "⭕", None),
    ("blond", "blond", "A1", "👱", None),
    ("brun", "brünett", "A2", "🤎", None),
    ("roux", "rothaarig", "B1", "🦰", None),
    ("chauve", "kahl", "B1", "🧑‍🦲", None),
    ("barbu", "bärtig", "B1", "🧔", None),

    # ============ QUALITÉS INTELLECTUELLES (10) ============
    ("brillant", "brillant", "B1", "💫", None),
    ("doué", "begabt", "B1", "🌟", None),
    ("perspicace", "scharfsinnig", "B2", "🔍", None),
    ("ignorant", "unwissend", "B2", "❓", None),
    ("cultivé", "gebildet", "B2", "📚", None),
    ("logique", "logisch", "B1", "🧠", None),
    ("rationnel", "rational", "B2", "📊", None),
    ("naïf", "naiv", "B1", "🌼", None),
    ("astucieux", "schlau", "B1", "🦊", None),
    ("compétent", "kompetent", "B1", "✅", None),

    # ============ QUALITÉS SOCIALES (10) ============
    ("sociable", "gesellig", "B1", "👥", None),
    ("solitaire", "einsam", "B1", "🚶", None),
    ("populaire", "beliebt", "B1", "⭐", None),
    ("respecté", "respektiert", "B1", "🤝", None),
    ("admiré", "bewundert", "B1", "🌟", None),
    ("influent", "einflussreich", "B2", "🌊", None),
    ("ouvert d'esprit", "aufgeschlossen", "B2", "🌈", None),
    ("borné", "engstirnig", "B2", "🚫", None),
    ("tolérant", "tolerant", "B1", "🤝", None),
    ("intolérant", "intolerant", "B1", "🚫", None),

    # ============ TEMPS & FRÉQUENCE (5) ============
    ("ponctuel", "pünktlich", "A2", "⏰", None),
    ("en retard", "verspätet", "A2", "⏰", None),
    ("précoce", "früh", "B1", "🌅", None),
    ("tardif", "spät", "B1", "🌃", None),
    ("constant", "ständig", "B1", "♾️", None),

    # ============ ABSTRAIT B2 (9) ============
    ("complexe", "komplex", "B2", "🌀", None),
    ("ambigu", "mehrdeutig", "B2", "❓", None),
    ("évident", "offensichtlich", "B1", "👁️", None),
    ("subtil", "subtil", "B2", "🎨", None),
    ("crucial", "entscheidend", "B2", "❗", None),
    ("efficace", "wirksam", "B1", "✅", None),
    ("inefficace", "unwirksam", "B2", "❌", None),
    ("légitime", "rechtmäßig", "B2", "⚖️", None),
    ("controversé", "umstritten", "B2", "🗣️", None),
]

# ============================================================
# PRÉPOSITIONS — Ajout de 25 (51 → 76)
# Focus : locutions prépositionnelles
# ============================================================
PREPOSITIONS_EXISTANTES = [
    ("avec", "mit", "A1", "🤝"),
    ("sans", "ohne", "A1", "🚫"),
    ("pour", "für", "A1", "🎁"),
    ("contre", "gegen", "A1", "⚔️"),
    ("dans", "in", "A1", "📦"),
    ("sur", "auf", "A1", "⬆️"),
    ("sous", "unter", "A1", "⬇️"),
    ("devant", "vor", "A1", "👉"),
    ("derrière", "hinter", "A1", "👈"),
    ("entre", "zwischen", "A1", "↔️"),
    ("à côté de", "neben", "A1", "👫"),
    ("au-dessus", "über", "A2", "⬆️"),
    ("autour", "um", "A2", "🔄"),
    ("près de", "bei", "A1", "📍"),
    ("loin de", "weit von", "A2", "🌍"),
    ("vers", "zu", "A1", "➡️"),
    ("à travers", "durch", "A2", "↔️"),
    ("le long de", "entlang", "B1", "📏"),
    ("en face de", "gegenüber", "B1", "🪞"),
    ("au milieu de", "in der Mitte", "B1", "🎯"),
    ("avant", "vor", "A1", "⏪"),
    ("après", "nach", "A1", "⏩"),
    ("pendant", "während", "A2", "⏳"),
    ("depuis", "seit", "A1", "📅"),
    ("jusqu'à", "bis", "A1", "🏁"),
    ("à partir de", "ab", "A2", "▶️"),
    ("vers (temps)", "gegen", "A2", "🕐"),
    ("en", "in", "A1", "📅"),
    ("au", "am", "A1", "📍"),
    ("de", "von", "A1", "📍"),
    ("à", "zu", "A1", "🎯"),
    ("chez", "bei", "A1", "🏡"),
    ("d'origine", "aus", "A1", "🏠"),
    ("avec (moyen)", "mit", "A1", "🛠️"),
    ("par", "durch", "A2", "↔️"),
    ("en (transport)", "mit", "A1", "🚗"),
    ("selon", "laut", "B1", "📖"),
    ("d'après", "nach", "B1", "💬"),
    ("à cause de", "wegen", "B1", "❓"),
    ("grâce à", "dank", "B1", "🙏"),
    ("malgré", "trotz", "B1", "💪"),
    ("pour (but)", "für", "A1", "🎯"),
    ("au lieu de", "anstatt", "B1", "🔄"),
    ("à propos de", "über", "A2", "💬"),
    ("au sujet de", "bezüglich", "B2", "📋"),
    ("en dépit de", "ungeachtet", "B2", "🛡️"),
    ("au-delà de", "jenseits", "B2", "🌍"),
    ("en raison de", "aufgrund", "B2", "📊"),
    ("conformément à", "gemäß", "B2", "📜"),
    ("dès", "ab", "B1", "▶️"),
    ("durant", "während", "B1", "⏳"),
]

PREPOSITIONS_NOUVELLES = [
    # ============ LOCUTIONS SPATIALES (8) ============
    ("au bord de", "am Rande von", "B1", "🏞️"),
    ("au pied de", "am Fuße von", "B1", "🏔️"),
    ("au sommet de", "auf dem Gipfel von", "B1", "🏔️"),
    ("au centre de", "im Zentrum von", "B1", "🎯"),
    ("à l'intérieur de", "innerhalb von", "B2", "📦"),
    ("à l'extérieur de", "außerhalb von", "B2", "🌍"),
    ("aux alentours de", "in der Umgebung von", "B2", "📍"),
    ("dans la direction de", "in Richtung", "B1", "➡️"),

    # ============ LOCUTIONS TEMPORELLES (5) ============
    ("au cours de", "im Laufe von", "B1", "⏳"),
    ("au moment de", "im Moment von", "B1", "⏰"),
    ("en attendant", "in Erwartung", "B2", "⏰"),
    ("à l'occasion de", "anlässlich", "B2", "🎉"),
    ("au terme de", "am Ende von", "B2", "🏁"),

    # ============ LOCUTIONS CAUSALES & LOGIQUES (8) ============
    ("en faveur de", "zugunsten von", "B2", "👍"),
    ("au détriment de", "zum Nachteil von", "B2", "👎"),
    ("compte tenu de", "in Anbetracht", "B2", "📊"),
    ("indépendamment de", "unabhängig von", "B2", "🆓"),
    ("par rapport à", "im Vergleich zu", "B1", "⚖️"),
    ("en comparaison avec", "im Vergleich zu", "B2", "⚖️"),
    ("contrairement à", "im Gegensatz zu", "B2", "🔄"),
    ("en accord avec", "in Übereinstimmung mit", "B2", "🤝"),

    # ============ LOCUTIONS MODALES (4) ============
    ("à l'aide de", "mit Hilfe von", "B1", "🛠️"),
    ("au moyen de", "mittels", "B2", "🔧"),
    ("à condition de", "unter der Bedingung", "B2", "📜"),
    ("en vue de", "im Hinblick auf", "B2", "🎯"),
]

# ============================================================
# EXPRESSIONS — Ajout de 85 (170 → 255)
# Focus : idiomes B1-B2, expressions formelles
# ============================================================
EXPRESSIONS_EXISTANTES = [
    ("Bonjour", "Guten Tag", "A1", "👋"),
    ("Salut", "Hallo", "A1", "👋"),
    ("Bonsoir", "Guten Abend", "A1", "🌆"),
    ("Bonne nuit", "Gute Nacht", "A1", "🌙"),
    ("Au revoir", "Auf Wiedersehen", "A1", "👋"),
    ("À bientôt", "Bis bald", "A1", "👋"),
    ("À demain", "Bis morgen", "A1", "📅"),
    ("À tout à l'heure", "Bis später", "A1", "⏰"),
    ("Bonne journée", "Schönen Tag", "A1", "☀️"),
    ("Bonne soirée", "Schönen Abend", "A1", "🌆"),
    ("Bon week-end", "Schönes Wochenende", "A1", "🎉"),
    ("Bonjour le matin", "Guten Morgen", "A1", "🌅"),
    ("Bienvenue", "Willkommen", "A1", "🚪"),
    ("Tchüss", "Tschüss", "A1", "👋"),
    ("Merci", "Danke", "A1", "🙏"),
    ("Merci beaucoup", "Danke sehr", "A1", "🙏"),
    ("S'il vous plaît", "Bitte", "A1", "🤲"),
    ("De rien", "Gern geschehen", "A1", "😊"),
    ("Avec plaisir", "Mit Vergnügen", "A2", "😊"),
    ("Pardon", "Entschuldigung", "A1", "🙇"),
    ("Excusez-moi", "Entschuldigen Sie", "A1", "🙇"),
    ("Désolé", "Es tut mir leid", "A1", "😔"),
    ("Pas de problème", "Kein Problem", "A1", "👌"),
    ("Ce n'est rien", "Macht nichts", "A2", "🤷"),
    ("Je m'appelle", "Ich heiße", "A1", "🏷️"),
    ("Comment t'appelles-tu", "Wie heißt du", "A1", "❓"),
    ("Enchanté", "Freut mich", "A1", "🤝"),
    ("J'ai X ans", "Ich bin X Jahre alt", "A1", "🎂"),
    ("Je viens de", "Ich komme aus", "A1", "🌍"),
    ("J'habite à", "Ich wohne in", "A1", "🏠"),
    ("Je parle français", "Ich spreche Französisch", "A1", "💬"),
    ("Je suis étudiant", "Ich bin Student", "A1", "🎓"),
    ("Comment ça va", "Wie geht's", "A1", "💬"),
    ("Comment allez-vous", "Wie geht es Ihnen", "A1", "💬"),
    ("Ça va bien", "Es geht mir gut", "A1", "👍"),
    ("Ça va mal", "Es geht mir schlecht", "A1", "👎"),
    ("Quoi de neuf", "Was gibt's Neues", "A2", "📰"),
    ("Comment", "Wie", "A1", "❓"),
    ("Quoi", "Was", "A1", "❓"),
    ("Qui", "Wer", "A1", "❓"),
    ("Quand", "Wann", "A1", "📅"),
    ("Où", "Wo", "A1", "📍"),
    ("Pourquoi", "Warum", "A1", "❓"),
    ("Combien", "Wie viel", "A1", "🔢"),
    ("Quel âge", "Wie alt", "A1", "🎂"),
    ("Quelle heure est-il", "Wie spät ist es", "A1", "🕐"),
    ("Oui", "Ja", "A1", "✅"),
    ("Non", "Nein", "A1", "❌"),
    ("Peut-être", "Vielleicht", "A1", "🤷"),
    ("D'accord", "Einverstanden", "A1", "👌"),
    ("Bien sûr", "Natürlich", "A1", "✅"),
    ("Évidemment", "Selbstverständlich", "A2", "✅"),
    ("Pas du tout", "Überhaupt nicht", "A2", "❌"),
    ("Absolument", "Absolut", "A2", "💯"),
    ("Je ne sais pas", "Ich weiß nicht", "A1", "🤷"),
    ("Je crois que oui", "Ich glaube ja", "A2", "🤔"),
    ("Je crois que non", "Ich glaube nicht", "A2", "🤔"),
    ("Je ne comprends pas", "Ich verstehe nicht", "A1", "🤔"),
    ("Je comprends", "Ich verstehe", "A1", "💡"),
    ("Pouvez-vous répéter", "Können Sie wiederholen", "A1", "🔁"),
    ("Plus lentement", "Langsamer bitte", "A1", "🐌"),
    ("Parlez-vous français", "Sprechen Sie Französisch", "A1", "🇫🇷"),
    ("Parlez-vous anglais", "Sprechen Sie Englisch", "A1", "🇬🇧"),
    ("Comment dit-on", "Wie sagt man", "A1", "💬"),
    ("Qu'est-ce que ça veut dire", "Was bedeutet das", "A1", "❓"),
    ("Je suis content", "Ich bin glücklich", "A1", "😊"),
    ("Je suis triste", "Ich bin traurig", "A1", "😢"),
    ("Je suis fatigué", "Ich bin müde", "A1", "😴"),
    ("J'ai faim", "Ich habe Hunger", "A1", "🍽️"),
    ("J'ai soif", "Ich habe Durst", "A1", "🥤"),
    ("J'ai froid", "Mir ist kalt", "A1", "🥶"),
    ("J'ai chaud", "Mir ist warm", "A1", "🥵"),
    ("J'ai peur", "Ich habe Angst", "A2", "😨"),
    ("Je suis malade", "Ich bin krank", "A1", "🤒"),
    ("Ça me plaît", "Das gefällt mir", "A1", "😊"),
    ("Ça ne me plaît pas", "Das gefällt mir nicht", "A1", "😒"),
    ("J'aime", "Ich mag", "A1", "❤️"),
    ("Je n'aime pas", "Ich mag nicht", "A1", "💔"),
    ("J'adore", "Ich liebe", "A1", "😍"),
    ("Je déteste", "Ich hasse", "A2", "😤"),
    ("Félicitations", "Glückwunsch", "A1", "🎉"),
    ("Bravo", "Bravo", "A1", "👏"),
    ("Joyeux anniversaire", "Alles Gute zum Geburtstag", "A1", "🎂"),
    ("Joyeux Noël", "Frohe Weihnachten", "A1", "🎄"),
    ("Bonne année", "Frohes neues Jahr", "A1", "🎊"),
    ("Bonnes vacances", "Schöne Ferien", "A1", "🏖️"),
    ("Bonne chance", "Viel Glück", "A1", "🍀"),
    ("Bon courage", "Viel Erfolg", "A2", "💪"),
    ("Bon appétit", "Guten Appetit", "A1", "🍽️"),
    ("Santé", "Prost", "A1", "🍻"),
    ("À ta santé", "Zum Wohl", "A2", "🥂"),
    ("Bon voyage", "Gute Reise", "A1", "✈️"),
    ("Bon rétablissement", "Gute Besserung", "A1", "💊"),
    ("Je voudrais", "Ich möchte", "A1", "🤲"),
    ("L'addition", "Die Rechnung", "A1", "🧾"),
    ("Combien ça coûte", "Wie viel kostet das", "A1", "💲"),
    ("C'est trop cher", "Das ist zu teuer", "A1", "💸"),
    ("Avez-vous", "Haben Sie", "A1", "❓"),
    ("Je prendrai", "Ich nehme", "A1", "✋"),
    ("Encore un peu", "Noch ein bisschen", "A2", "➕"),
    ("Ça suffit", "Das reicht", "A2", "🛑"),
    ("La carte", "Die Speisekarte", "A1", "📋"),
    ("Une table pour deux", "Einen Tisch für zwei", "A2", "🍽️"),
    ("Où est", "Wo ist", "A1", "❓"),
    ("À gauche", "Links", "A1", "👈"),
    ("À droite", "Rechts", "A1", "👉"),
    ("Tout droit", "Geradeaus", "A1", "⬆️"),
    ("Ici", "Hier", "A1", "📍"),
    ("Là-bas", "Dort", "A1", "👉"),
    ("Près d'ici", "In der Nähe", "A2", "📍"),
    ("Loin", "Weit", "A1", "🌍"),
    ("Je suis perdu", "Ich habe mich verlaufen", "A2", "🗺️"),
    ("Aujourd'hui", "Heute", "A1", "📅"),
    ("Hier", "Gestern", "A1", "⏪"),
    ("Demain", "Morgen", "A1", "⏩"),
    ("Maintenant", "Jetzt", "A1", "⏰"),
    ("Plus tard", "Später", "A1", "⌛"),
    ("Bientôt", "Bald", "A1", "⏳"),
    ("Souvent", "Oft", "A1", "🔄"),
    ("Toujours", "Immer", "A1", "♾️"),
    ("Jamais", "Nie", "A1", "🚫"),
    ("Parfois", "Manchmal", "A1", "🔀"),
    ("Ça dépend", "Es kommt darauf an", "B1", "⚖️"),
    ("À mon avis", "Meiner Meinung nach", "B1", "💭"),
    ("Je pense que", "Ich denke, dass", "A2", "💭"),
    ("Si possible", "Wenn möglich", "B1", "🤔"),
    ("Bien entendu", "Selbstverständlich", "B1", "✅"),
    ("De toute façon", "Auf jeden Fall", "B1", "💪"),
    ("Au fait", "Übrigens", "B1", "💡"),
    ("D'ailleurs", "Übrigens", "B1", "💡"),
    ("En effet", "Tatsächlich", "B1", "✅"),
    ("C'est-à-dire", "Das heißt", "B1", "💬"),
    ("Par exemple", "Zum Beispiel", "A2", "💡"),
    ("En général", "Im Allgemeinen", "B1", "🌐"),
    ("En particulier", "Insbesondere", "B2", "🎯"),
    ("Tout d'abord", "Zuerst", "A2", "1️⃣"),
    ("Ensuite", "Dann", "A1", "➡️"),
    ("Finalement", "Schließlich", "A2", "🏁"),
    ("Cependant", "Jedoch", "B1", "⚖️"),
    ("Pourtant", "Doch", "A2", "🤔"),
    ("Au contraire", "Im Gegenteil", "B1", "🔄"),
    ("Heureusement", "Glücklicherweise", "B1", "🍀"),
    ("Malheureusement", "Leider", "A2", "😔"),
    ("Au secours", "Hilfe", "A1", "🆘"),
    ("Attention", "Achtung", "A1", "⚠️"),
    ("Appelez la police", "Rufen Sie die Polizei", "A2", "🚓"),
    ("Appelez un médecin", "Rufen Sie einen Arzt", "A2", "👨‍⚕️"),
    ("J'ai mal", "Es tut weh", "A1", "🤕"),
    ("Je me sens mal", "Mir ist schlecht", "A2", "🤢"),
    ("C'est une urgence", "Es ist ein Notfall", "B1", "🚨"),
    ("Pas mal", "Nicht schlecht", "A2", "👌"),
    ("Tant pis", "Pech gehabt", "B1", "🤷"),
    ("Tant mieux", "Umso besser", "B1", "😊"),
    ("Ça m'est égal", "Das ist mir egal", "B1", "🤷"),
    ("Et alors", "Na und", "B1", "🤨"),
    ("Allez-y", "Los geht's", "A2", "▶️"),
    ("Vas-y doucement", "Sei vorsichtig", "B1", "🐢"),
    ("Dépêche-toi", "Beeil dich", "A2", "⏰"),
    ("Attendez", "Warten Sie", "A1", "✋"),
    ("Calme-toi", "Beruhig dich", "B1", "😌"),
    ("Ne t'inquiète pas", "Mach dir keine Sorgen", "A2", "💆"),
    ("Tout va bien", "Alles ist gut", "A1", "👌"),
    ("C'est génial", "Das ist toll", "A1", "🤩"),
    ("C'est dommage", "Das ist schade", "A2", "😔"),
    ("Vraiment", "Wirklich", "A1", "💯"),
    ("Bien sûr que oui", "Aber sicher", "A2", "💯"),
    ("Quelle surprise", "Was für eine Überraschung", "B1", "😲"),
    ("Quel dommage", "Wie schade", "B1", "😔"),
    ("Tu plaisantes", "Du machst Witze", "B1", "😆"),
    ("Sans blague", "Ohne Witz", "B1", "😄"),
]

EXPRESSIONS_NOUVELLES = [
    # ============ IDIOMES ALLEMANDS COURANTS (20) ============
    ("Ce n'est pas ma tasse de thé", "Das ist nicht mein Ding", "B1", "🍵"),
    ("Tomber dans les pommes", "in Ohnmacht fallen", "B2", "🍎"),
    ("Avoir la pêche", "gut drauf sein", "B1", "🍑"),
    ("C'est du gâteau", "Das ist ein Kinderspiel", "B1", "🍰"),
    ("Coûter les yeux de la tête", "ein Vermögen kosten", "B2", "💎"),
    ("Avoir le coup de foudre", "Liebe auf den ersten Blick", "B1", "💘"),
    ("Faire d'une pierre deux coups", "zwei Fliegen mit einer Klappe", "B2", "🎯"),
    ("Être dans la lune", "in Gedanken versunken sein", "B2", "🌙"),
    ("Avoir un poil dans la main", "stinkfaul sein", "B2", "💤"),
    ("Donner sa langue au chat", "ich gebe auf", "B2", "🐱"),
    ("Mettre les pieds dans le plat", "ins Fettnäpfchen treten", "B2", "🍽️"),
    ("Avoir le moral à zéro", "im Keller sein", "B1", "📉"),
    ("Sauter du coq à l'âne", "vom Hundertsten ins Tausendste", "B2", "🐓"),
    ("Avoir d'autres chats à fouetter", "andere Sorgen haben", "B2", "🐱"),
    ("Casser les pieds", "auf die Nerven gehen", "B1", "🦶"),
    ("Avoir du pain sur la planche", "viel zu tun haben", "B1", "🍞"),
    ("Tirer son chapeau", "Hut ab", "B2", "🎩"),
    ("Mettre la main à la pâte", "mit anpacken", "B2", "🤝"),
    ("Tourner autour du pot", "um den heißen Brei reden", "B2", "🍲"),
    ("Tomber des nues", "aus allen Wolken fallen", "B2", "☁️"),

    # ============ EXPRESSIONS FORMELLES (15) ============
    ("Veuillez agréer", "Mit freundlichen Grüßen", "B2", "✉️"),
    ("Je vous prie de", "Ich bitte Sie", "B1", "🙏"),
    ("Permettez-moi de", "Erlauben Sie mir", "B2", "🎩"),
    ("Je tiens à", "Ich möchte betonen", "B2", "💼"),
    ("Sauf erreur de ma part", "Wenn ich mich nicht irre", "B2", "🤔"),
    ("Pour autant que je sache", "Soweit ich weiß", "B2", "🧠"),
    ("Au demeurant", "Im Übrigen", "B2", "💬"),
    ("Force est de constater", "Es muss festgestellt werden", "B2", "👁️"),
    ("Il convient de", "Es ist angebracht", "B2", "✅"),
    ("Il s'avère que", "Es stellt sich heraus", "B2", "🔍"),
    ("Dans la mesure où", "Insofern", "B2", "📏"),
    ("Étant donné que", "Da", "B1", "📊"),
    ("En vertu de", "Aufgrund von", "B2", "📜"),
    ("Quant à", "Was betrifft", "B2", "💭"),
    ("Toutefois", "Allerdings", "B1", "⚖️"),

    # ============ EXPRESSIONS DE NUANCE (15) ============
    ("À première vue", "Auf den ersten Blick", "B1", "👁️"),
    ("À long terme", "Langfristig", "B1", "📅"),
    ("À court terme", "Kurzfristig", "B1", "⏰"),
    ("De temps en temps", "Ab und zu", "A2", "🔄"),
    ("Tôt ou tard", "Früher oder später", "B1", "⏰"),
    ("Petit à petit", "Nach und nach", "B1", "🐢"),
    ("Tout de suite", "Sofort", "A2", "⚡"),
    ("Sans cesse", "Ständig", "B1", "♾️"),
    ("À tour de rôle", "Reihum", "B2", "🔄"),
    ("De plus en plus", "Immer mehr", "A2", "📈"),
    ("De moins en moins", "Immer weniger", "A2", "📉"),
    ("Plus ou moins", "Mehr oder weniger", "A2", "⚖️"),
    ("Pour ainsi dire", "Sozusagen", "B1", "💬"),
    ("En quelque sorte", "Gewissermaßen", "B2", "🤷"),
    ("D'une certaine manière", "In gewisser Weise", "B2", "💭"),

    # ============ EXPRESSIONS D'OPINION (10) ============
    ("Ça me semble", "Es scheint mir", "B1", "👁️"),
    ("Je suis convaincu que", "Ich bin überzeugt, dass", "B2", "💪"),
    ("Je doute que", "Ich bezweifle, dass", "B2", "🤔"),
    ("Personnellement", "Persönlich", "B1", "👤"),
    ("À mes yeux", "Aus meiner Sicht", "B2", "👁️"),
    ("Si je puis dire", "Wenn ich das sagen darf", "B2", "💬"),
    ("Selon moi", "Meiner Meinung nach", "B1", "💭"),
    ("Il me semble que", "Es scheint mir, dass", "B1", "🤔"),
    ("Je trouve que", "Ich finde, dass", "A2", "💡"),
    ("Honnêtement", "Ehrlich gesagt", "B1", "❤️"),

    # ============ EXPRESSIONS ÉMOTIONNELLES (10) ============
    ("Quel bonheur", "Was für ein Glück", "B1", "😊"),
    ("Ça me touche", "Das berührt mich", "B1", "🥺"),
    ("Je suis ravi", "Ich bin entzückt", "B1", "🥳"),
    ("Ça me dégoûte", "Das ekelt mich an", "B2", "🤢"),
    ("J'en ai marre", "Ich habe es satt", "B1", "😤"),
    ("J'en ai assez", "Mir reicht's", "B1", "🛑"),
    ("Ça m'énerve", "Das nervt mich", "B1", "😡"),
    ("Quel soulagement", "Welche Erleichterung", "B1", "😌"),
    ("Je suis sur les nerfs", "Ich bin total gestresst", "B2", "😰"),
    ("Ça me rend fou", "Das macht mich verrückt", "B1", "🤯"),

    # ============ EXPRESSIONS PRATIQUES (15) ============
    ("Au pire", "Im schlimmsten Fall", "B1", "⚠️"),
    ("Au mieux", "Im besten Fall", "B1", "🌟"),
    ("En cas de", "Im Falle von", "B1", "🚨"),
    ("Faute de", "Mangels", "B2", "🚫"),
    ("À défaut de", "In Ermangelung", "B2", "❌"),
    ("Histoire de", "Nur um zu", "B2", "💭"),
    ("Du coup", "Also", "B1", "➡️"),
    ("Bref", "Kurz gesagt", "B1", "📝"),
    ("En gros", "Im Großen und Ganzen", "B1", "🌐"),
    ("En somme", "Letztendlich", "B2", "🏁"),
    ("En définitive", "Letztlich", "B2", "🎯"),
    ("Pour faire court", "Um es kurz zu machen", "B2", "✂️"),
    ("Soit dit en passant", "Nebenbei bemerkt", "B2", "💬"),
    ("Pour la petite histoire", "Übrigens", "B2", "📖"),
    ("Cela dit", "Allerdings", "B1", "⚖️"),
]


# ============================================================
# GÉNÉRATION
# ============================================================
def img_url(unsplash_id):
    return f"https://images.unsplash.com/photo-{unsplash_id}?w=600&h=450&fit=crop&q=80" if unsplash_id else ""

def entry_with_img(fr, de, art, level, emoji, img_id):
    obj = {"f": fr, "d": de, "l": level, "e": emoji}
    if art: obj["a"] = art
    if img_id: obj["i"] = img_id
    return obj

def entry_no_img(fr, de, level, emoji):
    return {"f": fr, "d": de, "l": level, "e": emoji}

NOMS = NOMS_EXISTANTS + NOMS_NOUVEAUX
VERBES = VERBES_EXISTANTS + VERBES_NOUVEAUX
ADJECTIFS = ADJECTIFS_EXISTANTS + ADJECTIFS_NOUVEAUX
PREPOSITIONS = PREPOSITIONS_EXISTANTES + PREPOSITIONS_NOUVELLES
EXPRESSIONS = EXPRESSIONS_EXISTANTES + EXPRESSIONS_NOUVELLES

data = {
    "noms": [entry_with_img(fr, de, art, lvl, em, iid) for fr, de, art, lvl, em, iid in NOMS],
    "verbes": [entry_with_img(fr, de, None, lvl, em, iid) for fr, de, lvl, em, iid in VERBES],
    "adjectifs": [entry_with_img(fr, de, None, lvl, em, iid) for fr, de, lvl, em, iid in ADJECTIFS],
    "prepositions": [entry_no_img(fr, de, lvl, em) for fr, de, lvl, em in PREPOSITIONS],
    "expressions": [entry_no_img(fr, de, lvl, em) for fr, de, lvl, em in EXPRESSIONS],
}

# Stats
print("\n=== STATISTIQUES FINALES ===\n")
for cat, words in data.items():
    levels = {}
    for w in words:
        l = w["l"]
        levels[l] = levels.get(l, 0) + 1
    total = len(words)
    breakdown = " | ".join([f"{l}: {n}" for l, n in sorted(levels.items())])
    print(f"{cat.upper():15} {total:4} mots   ({breakdown})")

grand_total = sum(len(w) for w in data.values())
print(f"\nGRAND TOTAL VOCABULAIRE : {grand_total} mots\n")

# Génération du fichier
js = "// Base de données vocabulaire allemand — Format compact\n"
js += "// f=french, d=german, a=article, l=level, e=emoji, i=unsplash_id\n\n"
js += "const VOCAB = "
js += json.dumps(data, ensure_ascii=False, separators=(',', ':'))
js += ";\n\n"
js += "const IMG_URL = (id) => `https://images.unsplash.com/photo-${id}?w=600&h=450&fit=crop&q=80`;\n"

with open('/home/claude/lernen-v2/public/data.js', 'w', encoding='utf-8') as f:
    f.write(js)

print(f"data.js mis à jour : {len(js)} caractères ({len(js)/1024:.1f} Ko)")
